export const QUERY_KEYS = {
  jobs: ['jobs'] as const,
  job: (id: string) => ['jobs', id] as const,
  jobsList: (filters: { status?: string; page?: number; limit?: number }) => ['jobs', 'list', filters] as const,
  recentJobs: ['jobs', 'recent'] as const,
  jobById: (id: string) => ['jobs', 'detail', id] as const,
  technicians: ['technicians'] as const,
  nearbyTechnicians: (lat?: number, lng?: number) => ['technicians', 'nearby', lat, lng] as const,
  materials: ['materials'] as const,
  quotations: ['quotations'] as const,
  quotation: (id: string) => ['quotations', id] as const,
  notifications: ['notifications'] as const,
  earnings: ['earnings'] as const,
  adminOverview: ['admin', 'overview'] as const,
  adminJobStats: (from: string, to: string) => ['admin', 'analytics', 'jobs', from, to] as const,
  adminRevenueStats: (from: string, to: string) => ['admin', 'analytics', 'revenue', from, to] as const,
  topTechnicians: (limit?: number) => ['admin', 'analytics', 'technicians', limit] as const,
  supplierAnalytics: ['supplier', 'analytics'] as const,
  adminUsers: (search: string, role: string) => ['admin', 'users', search, role] as const,
  adminJobs: ['admin', 'jobs'] as const,
  supplierStats: ['supplier', 'stats'] as const,
  orders: ['orders'] as const,
  nearbySuppliers: 'nearbySuppliers' as const,
  reviews: ['reviews'] as const,
  disputes: ['disputes'] as const,
  dispute: (id: string) => ['disputes', id] as const,
  adminDisputes: ['admin', 'disputes'] as const,
  scheduledJobs: ['jobs', 'scheduled'] as const,
}
