// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: review/v1/review.proto

package reviewv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReviewPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ReviewerId    string                 `protobuf:"bytes,3,opt,name=reviewer_id,json=reviewerId,proto3" json:"reviewer_id,omitempty"`
	RevieweeId    string                 `protobuf:"bytes,4,opt,name=reviewee_id,json=revieweeId,proto3" json:"reviewee_id,omitempty"`
	ReviewerName  string                 `protobuf:"bytes,5,opt,name=reviewer_name,json=reviewerName,proto3" json:"reviewer_name,omitempty"`
	Rating        int32                  `protobuf:"varint,6,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,7,opt,name=comment,proto3" json:"comment,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,8,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewPB) Reset() {
	*x = ReviewPB{}
	mi := &file_review_v1_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewPB) ProtoMessage() {}

func (x *ReviewPB) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewPB.ProtoReflect.Descriptor instead.
func (*ReviewPB) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{0}
}

func (x *ReviewPB) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReviewPB) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReviewPB) GetReviewerId() string {
	if x != nil {
		return x.ReviewerId
	}
	return ""
}

func (x *ReviewPB) GetRevieweeId() string {
	if x != nil {
		return x.RevieweeId
	}
	return ""
}

func (x *ReviewPB) GetReviewerName() string {
	if x != nil {
		return x.ReviewerName
	}
	return ""
}

func (x *ReviewPB) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ReviewPB) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ReviewPB) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *ReviewPB) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SubmitReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	RevieweeId    string                 `protobuf:"bytes,2,opt,name=reviewee_id,json=revieweeId,proto3" json:"reviewee_id,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,5,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitReviewRequest) Reset() {
	*x = SubmitReviewRequest{}
	mi := &file_review_v1_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitReviewRequest) ProtoMessage() {}

func (x *SubmitReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitReviewRequest.ProtoReflect.Descriptor instead.
func (*SubmitReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitReviewRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitReviewRequest) GetRevieweeId() string {
	if x != nil {
		return x.RevieweeId
	}
	return ""
}

func (x *SubmitReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *SubmitReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *SubmitReviewRequest) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

type SubmitReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *ReviewPB              `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitReviewResponse) Reset() {
	*x = SubmitReviewResponse{}
	mi := &file_review_v1_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitReviewResponse) ProtoMessage() {}

func (x *SubmitReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitReviewResponse.ProtoReflect.Descriptor instead.
func (*SubmitReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitReviewResponse) GetReview() *ReviewPB {
	if x != nil {
		return x.Review
	}
	return nil
}

type GetReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RevieweeId    string                 `protobuf:"bytes,1,opt,name=reviewee_id,json=revieweeId,proto3" json:"reviewee_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsRequest) Reset() {
	*x = GetReviewsRequest{}
	mi := &file_review_v1_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsRequest) ProtoMessage() {}

func (x *GetReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsRequest.ProtoReflect.Descriptor instead.
func (*GetReviewsRequest) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{3}
}

func (x *GetReviewsRequest) GetRevieweeId() string {
	if x != nil {
		return x.RevieweeId
	}
	return ""
}

func (x *GetReviewsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetReviewsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*ReviewPB            `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	AverageRating float64                `protobuf:"fixed64,3,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	TotalRatings  int32                  `protobuf:"varint,4,opt,name=total_ratings,json=totalRatings,proto3" json:"total_ratings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsResponse) Reset() {
	*x = GetReviewsResponse{}
	mi := &file_review_v1_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsResponse) ProtoMessage() {}

func (x *GetReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsResponse.ProtoReflect.Descriptor instead.
func (*GetReviewsResponse) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{4}
}

func (x *GetReviewsResponse) GetReviews() []*ReviewPB {
	if x != nil {
		return x.Reviews
	}
	return nil
}

func (x *GetReviewsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetReviewsResponse) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *GetReviewsResponse) GetTotalRatings() int32 {
	if x != nil {
		return x.TotalRatings
	}
	return 0
}

var File_review_v1_review_proto protoreflect.FileDescriptor

const file_review_v1_review_proto_rawDesc = "" +
	"\n" +
	"\x16review/v1/review.proto\x12\treview.v1\x1a\x1cgoogle/api/annotations.proto\"\x88\x02\n" +
	"\bReviewPB\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vreviewer_id\x18\x03 \x01(\tR\n" +
	"reviewerId\x12\x1f\n" +
	"\vreviewee_id\x18\x04 \x01(\tR\n" +
	"revieweeId\x12#\n" +
	"\rreviewer_name\x18\x05 \x01(\tR\freviewerName\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\a \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"image_urls\x18\b \x03(\tR\timageUrls\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"\x9e\x01\n" +
	"\x13SubmitReviewRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vreviewee_id\x18\x02 \x01(\tR\n" +
	"revieweeId\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x05 \x03(\tR\timageUrls\"C\n" +
	"\x14SubmitReviewResponse\x12+\n" +
	"\x06review\x18\x01 \x01(\v2\x13.review.v1.ReviewPBR\x06review\"^\n" +
	"\x11GetReviewsRequest\x12\x1f\n" +
	"\vreviewee_id\x18\x01 \x01(\tR\n" +
	"revieweeId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xa5\x01\n" +
	"\x12GetReviewsResponse\x12-\n" +
	"\areviews\x18\x01 \x03(\v2\x13.review.v1.ReviewPBR\areviews\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12%\n" +
	"\x0eaverage_rating\x18\x03 \x01(\x01R\raverageRating\x12#\n" +
	"\rtotal_ratings\x18\x04 \x01(\x05R\ftotalRatings2\xf2\x01\n" +
	"\rReviewService\x12g\n" +
	"\fSubmitReview\x12\x1e.review.v1.SubmitReviewRequest\x1a\x1f.review.v1.SubmitReviewResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/reviews\x12x\n" +
	"\n" +
	"GetReviews\x12\x1c.review.v1.GetReviewsRequest\x1a\x1d.review.v1.GetReviewsResponse\"-\x82\xd3\xe4\x93\x02'\x12%/v1/technicians/{reviewee_id}/reviewsBQZOgithub.com/yourname/fixflow-backend/internal/adapter/grpc/pb/review/v1;reviewv1b\x06proto3"

var (
	file_review_v1_review_proto_rawDescOnce sync.Once
	file_review_v1_review_proto_rawDescData []byte
)

func file_review_v1_review_proto_rawDescGZIP() []byte {
	file_review_v1_review_proto_rawDescOnce.Do(func() {
		file_review_v1_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_review_v1_review_proto_rawDesc), len(file_review_v1_review_proto_rawDesc)))
	})
	return file_review_v1_review_proto_rawDescData
}

var file_review_v1_review_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_review_v1_review_proto_goTypes = []any{
	(*ReviewPB)(nil),             // 0: review.v1.ReviewPB
	(*SubmitReviewRequest)(nil),  // 1: review.v1.SubmitReviewRequest
	(*SubmitReviewResponse)(nil), // 2: review.v1.SubmitReviewResponse
	(*GetReviewsRequest)(nil),    // 3: review.v1.GetReviewsRequest
	(*GetReviewsResponse)(nil),   // 4: review.v1.GetReviewsResponse
}
var file_review_v1_review_proto_depIdxs = []int32{
	0, // 0: review.v1.SubmitReviewResponse.review:type_name -> review.v1.ReviewPB
	0, // 1: review.v1.GetReviewsResponse.reviews:type_name -> review.v1.ReviewPB
	1, // 2: review.v1.ReviewService.SubmitReview:input_type -> review.v1.SubmitReviewRequest
	3, // 3: review.v1.ReviewService.GetReviews:input_type -> review.v1.GetReviewsRequest
	2, // 4: review.v1.ReviewService.SubmitReview:output_type -> review.v1.SubmitReviewResponse
	4, // 5: review.v1.ReviewService.GetReviews:output_type -> review.v1.GetReviewsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_review_v1_review_proto_init() }
func file_review_v1_review_proto_init() {
	if File_review_v1_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_review_v1_review_proto_rawDesc), len(file_review_v1_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_review_v1_review_proto_goTypes,
		DependencyIndexes: file_review_v1_review_proto_depIdxs,
		MessageInfos:      file_review_v1_review_proto_msgTypes,
	}.Build()
	File_review_v1_review_proto = out.File
	file_review_v1_review_proto_goTypes = nil
	file_review_v1_review_proto_depIdxs = nil
}
