// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: payment/v1/payment.proto

package paymentv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MaterialItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,3,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterialItem) Reset() {
	*x = MaterialItem{}
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterialItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialItem) ProtoMessage() {}

func (x *MaterialItem) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialItem.ProtoReflect.Descriptor instead.
func (*MaterialItem) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *MaterialItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MaterialItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *MaterialItem) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

type GenerateInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	LabourCharge  float64                `protobuf:"fixed64,2,opt,name=labour_charge,json=labourCharge,proto3" json:"labour_charge,omitempty"`
	MaterialItems []*MaterialItem        `protobuf:"bytes,3,rep,name=material_items,json=materialItems,proto3" json:"material_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateInvoiceRequest) Reset() {
	*x = GenerateInvoiceRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInvoiceRequest) ProtoMessage() {}

func (x *GenerateInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInvoiceRequest.ProtoReflect.Descriptor instead.
func (*GenerateInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateInvoiceRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GenerateInvoiceRequest) GetLabourCharge() float64 {
	if x != nil {
		return x.LabourCharge
	}
	return 0
}

func (x *GenerateInvoiceRequest) GetMaterialItems() []*MaterialItem {
	if x != nil {
		return x.MaterialItems
	}
	return nil
}

type InvoiceItemPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,3,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Total         float64                `protobuf:"fixed64,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceItemPB) Reset() {
	*x = InvoiceItemPB{}
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceItemPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceItemPB) ProtoMessage() {}

func (x *InvoiceItemPB) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceItemPB.ProtoReflect.Descriptor instead.
func (*InvoiceItemPB) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *InvoiceItemPB) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InvoiceItemPB) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *InvoiceItemPB) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *InvoiceItemPB) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GenerateInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	PdfUrl        string                 `protobuf:"bytes,2,opt,name=pdf_url,json=pdfUrl,proto3" json:"pdf_url,omitempty"`
	Total         float64                `protobuf:"fixed64,3,opt,name=total,proto3" json:"total,omitempty"`
	LineItems     []*InvoiceItemPB       `protobuf:"bytes,4,rep,name=line_items,json=lineItems,proto3" json:"line_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateInvoiceResponse) Reset() {
	*x = GenerateInvoiceResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInvoiceResponse) ProtoMessage() {}

func (x *GenerateInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInvoiceResponse.ProtoReflect.Descriptor instead.
func (*GenerateInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateInvoiceResponse) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *GenerateInvoiceResponse) GetPdfUrl() string {
	if x != nil {
		return x.PdfUrl
	}
	return ""
}

func (x *GenerateInvoiceResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GenerateInvoiceResponse) GetLineItems() []*InvoiceItemPB {
	if x != nil {
		return x.LineItems
	}
	return nil
}

type CreatePaymentOrderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePaymentOrderRequest) Reset() {
	*x = CreatePaymentOrderRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentOrderRequest) ProtoMessage() {}

func (x *CreatePaymentOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentOrderRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentOrderRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePaymentOrderRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CreatePaymentOrderRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreatePaymentOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	KeyId         string                 `protobuf:"bytes,4,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentOrderResponse) Reset() {
	*x = CreatePaymentOrderResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentOrderResponse) ProtoMessage() {}

func (x *CreatePaymentOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentOrderResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentOrderResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePaymentOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreatePaymentOrderResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentOrderResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentOrderResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type VerifyAndCaptureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAndCaptureRequest) Reset() {
	*x = VerifyAndCaptureRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAndCaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAndCaptureRequest) ProtoMessage() {}

func (x *VerifyAndCaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAndCaptureRequest.ProtoReflect.Descriptor instead.
func (*VerifyAndCaptureRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyAndCaptureRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *VerifyAndCaptureRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *VerifyAndCaptureRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type VerifyAndCaptureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PaymentId     string                 `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAndCaptureResponse) Reset() {
	*x = VerifyAndCaptureResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAndCaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAndCaptureResponse) ProtoMessage() {}

func (x *VerifyAndCaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAndCaptureResponse.ProtoReflect.Descriptor instead.
func (*VerifyAndCaptureResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyAndCaptureResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifyAndCaptureResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{8}
}

func (x *GetHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PaymentPB struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId             string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	CustomerId        string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	TechnicianId      string                 `protobuf:"bytes,4,opt,name=technician_id,json=technicianId,proto3" json:"technician_id,omitempty"`
	Amount            float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency          string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status            string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	RazorpayOrderId   string                 `protobuf:"bytes,8,opt,name=razorpay_order_id,json=razorpayOrderId,proto3" json:"razorpay_order_id,omitempty"`
	RazorpayPaymentId string                 `protobuf:"bytes,9,opt,name=razorpay_payment_id,json=razorpayPaymentId,proto3" json:"razorpay_payment_id,omitempty"`
	IdempotencyKey    string                 `protobuf:"bytes,10,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	FailureReason     string                 `protobuf:"bytes,11,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PaymentPB) Reset() {
	*x = PaymentPB{}
	mi := &file_payment_v1_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentPB) ProtoMessage() {}

func (x *PaymentPB) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentPB.ProtoReflect.Descriptor instead.
func (*PaymentPB) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{9}
}

func (x *PaymentPB) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentPB) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PaymentPB) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *PaymentPB) GetTechnicianId() string {
	if x != nil {
		return x.TechnicianId
	}
	return ""
}

func (x *PaymentPB) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentPB) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentPB) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentPB) GetRazorpayOrderId() string {
	if x != nil {
		return x.RazorpayOrderId
	}
	return ""
}

func (x *PaymentPB) GetRazorpayPaymentId() string {
	if x != nil {
		return x.RazorpayPaymentId
	}
	return ""
}

func (x *PaymentPB) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *PaymentPB) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *PaymentPB) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PaymentPB) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*PaymentPB           `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{10}
}

func (x *GetHistoryResponse) GetPayments() []*PaymentPB {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *GetHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceRequest) Reset() {
	*x = GetInvoiceRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceRequest) ProtoMessage() {}

func (x *GetInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceRequest.ProtoReflect.Descriptor instead.
func (*GetInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{11}
}

func (x *GetInvoiceRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,3,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	CustomerName  string                 `protobuf:"bytes,4,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	TechName      string                 `protobuf:"bytes,5,opt,name=tech_name,json=techName,proto3" json:"tech_name,omitempty"`
	ServiceType   string                 `protobuf:"bytes,6,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	LineItems     []*InvoiceItemPB       `protobuf:"bytes,7,rep,name=line_items,json=lineItems,proto3" json:"line_items,omitempty"`
	Subtotal      float64                `protobuf:"fixed64,8,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	TaxRate       float64                `protobuf:"fixed64,9,opt,name=tax_rate,json=taxRate,proto3" json:"tax_rate,omitempty"`
	TaxAmount     float64                `protobuf:"fixed64,10,opt,name=tax_amount,json=taxAmount,proto3" json:"tax_amount,omitempty"`
	Total         float64                `protobuf:"fixed64,11,opt,name=total,proto3" json:"total,omitempty"`
	PdfUrl        string                 `protobuf:"bytes,12,opt,name=pdf_url,json=pdfUrl,proto3" json:"pdf_url,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceResponse) Reset() {
	*x = GetInvoiceResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceResponse) ProtoMessage() {}

func (x *GetInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceResponse.ProtoReflect.Descriptor instead.
func (*GetInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{12}
}

func (x *GetInvoiceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetInvoiceResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetInvoiceResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *GetInvoiceResponse) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *GetInvoiceResponse) GetTechName() string {
	if x != nil {
		return x.TechName
	}
	return ""
}

func (x *GetInvoiceResponse) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *GetInvoiceResponse) GetLineItems() []*InvoiceItemPB {
	if x != nil {
		return x.LineItems
	}
	return nil
}

func (x *GetInvoiceResponse) GetSubtotal() float64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *GetInvoiceResponse) GetTaxRate() float64 {
	if x != nil {
		return x.TaxRate
	}
	return 0
}

func (x *GetInvoiceResponse) GetTaxAmount() float64 {
	if x != nil {
		return x.TaxAmount
	}
	return 0
}

func (x *GetInvoiceResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetInvoiceResponse) GetPdfUrl() string {
	if x != nil {
		return x.PdfUrl
	}
	return ""
}

func (x *GetInvoiceResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_payment_v1_payment_proto protoreflect.FileDescriptor

const file_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x18payment/v1/payment.proto\x12\n" +
	"payment.v1\x1a\x1cgoogle/api/annotations.proto\"k\n" +
	"\fMaterialItem\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x03 \x01(\x01R\tunitPrice\"\x95\x01\n" +
	"\x16GenerateInvoiceRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12#\n" +
	"\rlabour_charge\x18\x02 \x01(\x01R\flabourCharge\x12?\n" +
	"\x0ematerial_items\x18\x03 \x03(\v2\x18.payment.v1.MaterialItemR\rmaterialItems\"\x82\x01\n" +
	"\rInvoiceItemPB\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x03 \x01(\x01R\tunitPrice\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x01R\x05total\"\xa1\x01\n" +
	"\x17GenerateInvoiceResponse\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12\x17\n" +
	"\apdf_url\x18\x02 \x01(\tR\x06pdfUrl\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x01R\x05total\x128\n" +
	"\n" +
	"line_items\x18\x04 \x03(\v2\x19.payment.v1.InvoiceItemPBR\tlineItems\"[\n" +
	"\x19CreatePaymentOrderRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"\x82\x01\n" +
	"\x1aCreatePaymentOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x15\n" +
	"\x06key_id\x18\x04 \x01(\tR\x05keyId\"q\n" +
	"\x17VerifyAndCaptureRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\"S\n" +
	"\x18VerifyAndCaptureResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x02 \x01(\tR\tpaymentId\"=\n" +
	"\x11GetHistoryRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xae\x03\n" +
	"\tPaymentPB\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12#\n" +
	"\rtechnician_id\x18\x04 \x01(\tR\ftechnicianId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12*\n" +
	"\x11razorpay_order_id\x18\b \x01(\tR\x0frazorpayOrderId\x12.\n" +
	"\x13razorpay_payment_id\x18\t \x01(\tR\x11razorpayPaymentId\x12'\n" +
	"\x0fidempotency_key\x18\n" +
	" \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0efailure_reason\x18\v \x01(\tR\rfailureReason\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\"]\n" +
	"\x12GetHistoryResponse\x121\n" +
	"\bpayments\x18\x01 \x03(\v2\x15.payment.v1.PaymentPBR\bpayments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"*\n" +
	"\x11GetInvoiceRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x9d\x03\n" +
	"\x12GetInvoiceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x03 \x01(\tR\tpaymentId\x12#\n" +
	"\rcustomer_name\x18\x04 \x01(\tR\fcustomerName\x12\x1b\n" +
	"\ttech_name\x18\x05 \x01(\tR\btechName\x12!\n" +
	"\fservice_type\x18\x06 \x01(\tR\vserviceType\x128\n" +
	"\n" +
	"line_items\x18\a \x03(\v2\x19.payment.v1.InvoiceItemPBR\tlineItems\x12\x1a\n" +
	"\bsubtotal\x18\b \x01(\x01R\bsubtotal\x12\x19\n" +
	"\btax_rate\x18\t \x01(\x01R\ataxRate\x12\x1d\n" +
	"\n" +
	"tax_amount\x18\n" +
	" \x01(\x01R\ttaxAmount\x12\x14\n" +
	"\x05total\x18\v \x01(\x01R\x05total\x12\x17\n" +
	"\apdf_url\x18\f \x01(\tR\x06pdfUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt2\xf0\x04\n" +
	"\x0ePaymentService\x12{\n" +
	"\x0fGenerateInvoice\x12\".payment.v1.GenerateInvoiceRequest\x1a#.payment.v1.GenerateInvoiceResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/payments/invoice\x12\x82\x01\n" +
	"\x12CreatePaymentOrder\x12%.payment.v1.CreatePaymentOrderRequest\x1a&.payment.v1.CreatePaymentOrderResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/payments/order\x12}\n" +
	"\x10VerifyAndCapture\x12#.payment.v1.VerifyAndCaptureRequest\x1a$.payment.v1.VerifyAndCaptureResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/payments/verify\x12i\n" +
	"\n" +
	"GetHistory\x12\x1d.payment.v1.GetHistoryRequest\x1a\x1e.payment.v1.GetHistoryResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/payments/history\x12r\n" +
	"\n" +
	"GetInvoice\x12\x1d.payment.v1.GetInvoiceRequest\x1a\x1e.payment.v1.GetInvoiceResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/payments/invoice/{job_id}BSZQgithub.com/yourname/fixflow-backend/internal/adapter/grpc/pb/payment/v1;paymentv1b\x06proto3"

var (
	file_payment_v1_payment_proto_rawDescOnce sync.Once
	file_payment_v1_payment_proto_rawDescData []byte
)

func file_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)))
	})
	return file_payment_v1_payment_proto_rawDescData
}

var file_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_payment_v1_payment_proto_goTypes = []any{
	(*MaterialItem)(nil),               // 0: payment.v1.MaterialItem
	(*GenerateInvoiceRequest)(nil),     // 1: payment.v1.GenerateInvoiceRequest
	(*InvoiceItemPB)(nil),              // 2: payment.v1.InvoiceItemPB
	(*GenerateInvoiceResponse)(nil),    // 3: payment.v1.GenerateInvoiceResponse
	(*CreatePaymentOrderRequest)(nil),  // 4: payment.v1.CreatePaymentOrderRequest
	(*CreatePaymentOrderResponse)(nil), // 5: payment.v1.CreatePaymentOrderResponse
	(*VerifyAndCaptureRequest)(nil),    // 6: payment.v1.VerifyAndCaptureRequest
	(*VerifyAndCaptureResponse)(nil),   // 7: payment.v1.VerifyAndCaptureResponse
	(*GetHistoryRequest)(nil),          // 8: payment.v1.GetHistoryRequest
	(*PaymentPB)(nil),                  // 9: payment.v1.PaymentPB
	(*GetHistoryResponse)(nil),         // 10: payment.v1.GetHistoryResponse
	(*GetInvoiceRequest)(nil),          // 11: payment.v1.GetInvoiceRequest
	(*GetInvoiceResponse)(nil),         // 12: payment.v1.GetInvoiceResponse
}
var file_payment_v1_payment_proto_depIdxs = []int32{
	0,  // 0: payment.v1.GenerateInvoiceRequest.material_items:type_name -> payment.v1.MaterialItem
	2,  // 1: payment.v1.GenerateInvoiceResponse.line_items:type_name -> payment.v1.InvoiceItemPB
	9,  // 2: payment.v1.GetHistoryResponse.payments:type_name -> payment.v1.PaymentPB
	2,  // 3: payment.v1.GetInvoiceResponse.line_items:type_name -> payment.v1.InvoiceItemPB
	1,  // 4: payment.v1.PaymentService.GenerateInvoice:input_type -> payment.v1.GenerateInvoiceRequest
	4,  // 5: payment.v1.PaymentService.CreatePaymentOrder:input_type -> payment.v1.CreatePaymentOrderRequest
	6,  // 6: payment.v1.PaymentService.VerifyAndCapture:input_type -> payment.v1.VerifyAndCaptureRequest
	8,  // 7: payment.v1.PaymentService.GetHistory:input_type -> payment.v1.GetHistoryRequest
	11, // 8: payment.v1.PaymentService.GetInvoice:input_type -> payment.v1.GetInvoiceRequest
	3,  // 9: payment.v1.PaymentService.GenerateInvoice:output_type -> payment.v1.GenerateInvoiceResponse
	5,  // 10: payment.v1.PaymentService.CreatePaymentOrder:output_type -> payment.v1.CreatePaymentOrderResponse
	7,  // 11: payment.v1.PaymentService.VerifyAndCapture:output_type -> payment.v1.VerifyAndCaptureResponse
	10, // 12: payment.v1.PaymentService.GetHistory:output_type -> payment.v1.GetHistoryResponse
	12, // 13: payment.v1.PaymentService.GetInvoice:output_type -> payment.v1.GetInvoiceResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_payment_v1_payment_proto_init() }
func file_payment_v1_payment_proto_init() {
	if File_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_payment_v1_payment_proto_depIdxs,
		MessageInfos:      file_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_payment_v1_payment_proto = out.File
	file_payment_v1_payment_proto_goTypes = nil
	file_payment_v1_payment_proto_depIdxs = nil
}
