// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dispute/v1/dispute.proto

package disputev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DisputePB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	RaisedById    string                 `protobuf:"bytes,3,opt,name=raised_by_id,json=raisedById,proto3" json:"raised_by_id,omitempty"`
	RaisedByName  string                 `protobuf:"bytes,4,opt,name=raised_by_name,json=raisedByName,proto3" json:"raised_by_name,omitempty"`
	AgainstId     string                 `protobuf:"bytes,5,opt,name=against_id,json=againstId,proto3" json:"against_id,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	EvidenceUrls  []string               `protobuf:"bytes,8,rep,name=evidence_urls,json=evidenceUrls,proto3" json:"evidence_urls,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	AdminNote     string                 `protobuf:"bytes,10,opt,name=admin_note,json=adminNote,proto3" json:"admin_note,omitempty"`
	Action        string                 `protobuf:"bytes,11,opt,name=action,proto3" json:"action,omitempty"`
	ResolvedAt    string                 `protobuf:"bytes,12,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisputePB) Reset() {
	*x = DisputePB{}
	mi := &file_dispute_v1_dispute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisputePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisputePB) ProtoMessage() {}

func (x *DisputePB) ProtoReflect() protoreflect.Message {
	mi := &file_dispute_v1_dispute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisputePB.ProtoReflect.Descriptor instead.
func (*DisputePB) Descriptor() ([]byte, []int) {
	return file_dispute_v1_dispute_proto_rawDescGZIP(), []int{0}
}

func (x *DisputePB) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DisputePB) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *DisputePB) GetRaisedById() string {
	if x != nil {
		return x.RaisedById
	}
	return ""
}

func (x *DisputePB) GetRaisedByName() string {
	if x != nil {
		return x.RaisedByName
	}
	return ""
}

func (x *DisputePB) GetAgainstId() string {
	if x != nil {
		return x.AgainstId
	}
	return ""
}

func (x *DisputePB) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DisputePB) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DisputePB) GetEvidenceUrls() []string {
	if x != nil {
		return x.EvidenceUrls
	}
	return nil
}

func (x *DisputePB) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DisputePB) GetAdminNote() string {
	if x != nil {
		return x.AdminNote
	}
	return ""
}

func (x *DisputePB) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DisputePB) GetResolvedAt() string {
	if x != nil {
		return x.ResolvedAt
	}
	return ""
}

func (x *DisputePB) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type RaiseDisputeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaiseDisputeRequest) Reset() {
	*x = RaiseDisputeRequest{}
	mi := &file_dispute_v1_dispute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaiseDisputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaiseDisputeRequest) ProtoMessage() {}

func (x *RaiseDisputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dispute_v1_dispute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaiseDisputeRequest.ProtoReflect.Descriptor instead.
func (*RaiseDisputeRequest) Descriptor() ([]byte, []int) {
	return file_dispute_v1_dispute_proto_rawDescGZIP(), []int{1}
}

func (x *RaiseDisputeRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RaiseDisputeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RaiseDisputeRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RaiseDisputeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dispute       *DisputePB             `protobuf:"bytes,1,opt,name=dispute,proto3" json:"dispute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaiseDisputeResponse) Reset() {
	*x = RaiseDisputeResponse{}
	mi := &file_dispute_v1_dispute_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaiseDisputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaiseDisputeResponse) ProtoMessage() {}

func (x *RaiseDisputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dispute_v1_dispute_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaiseDisputeResponse.ProtoReflect.Descriptor instead.
func (*RaiseDisputeResponse) Descriptor() ([]byte, []int) {
	return file_dispute_v1_dispute_proto_rawDescGZIP(), []int{2}
}

func (x *RaiseDisputeResponse) GetDispute() *DisputePB {
	if x != nil {
		return x.Dispute
	}
	return nil
}

type UploadEvidenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisputeId     string                 `protobuf:"bytes,1,opt,name=dispute_id,json=disputeId,proto3" json:"dispute_id,omitempty"`
	FileUrl       string                 `protobuf:"bytes,2,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadEvidenceRequest) Reset() {
	*x = UploadEvidenceRequest{}
	mi := &file_dispute_v1_dispute_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadEvidenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadEvidenceRequest) ProtoMessage() {}

func (x *UploadEvidenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dispute_v1_dispute_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadEvidenceRequest.ProtoReflect.Descriptor instead.
func (*UploadEvidenceRequest) Descriptor() ([]byte, []int) {
	return file_dispute_v1_dispute_proto_rawDescGZIP(), []int{3}
}

func (x *UploadEvidenceRequest) GetDisputeId() string {
	if x != nil {
		return x.DisputeId
	}
	return ""
}

func (x *UploadEvidenceRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

type UploadEvidenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dispute       *DisputePB             `protobuf:"bytes,1,opt,name=dispute,proto3" json:"dispute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadEvidenceResponse) Reset() {
	*x = UploadEvidenceResponse{}
	mi := &file_dispute_v1_dispute_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadEvidenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadEvidenceResponse) ProtoMessage() {}

func (x *UploadEvidenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dispute_v1_dispute_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadEvidenceResponse.ProtoReflect.Descriptor instead.
func (*UploadEvidenceResponse) Descriptor() ([]byte, []int) {
	return file_dispute_v1_dispute_proto_rawDescGZIP(), []int{4}
}

func (x *UploadEvidenceResponse) GetDispute() *DisputePB {
	if x != nil {
		return x.Dispute
	}
	return nil
}

type ResolveDisputeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisputeId     string                 `protobuf:"bytes,1,opt,name=dispute_id,json=disputeId,proto3" json:"dispute_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	AdminNote     string                 `protobuf:"bytes,3,opt,name=admin_note,json=adminNote,proto3" json:"admin_note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveDisputeRequest) Reset() {
	*x = ResolveDisputeRequest{}
	mi := &file_dispute_v1_dispute_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveDisputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDisputeRequest) ProtoMessage() {}

func (x *ResolveDisputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dispute_v1_dispute_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDisputeRequest.ProtoReflect.Descriptor instead.
func (*ResolveDisputeRequest) Descriptor() ([]byte, []int) {
	return file_dispute_v1_dispute_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveDisputeRequest) GetDisputeId() string {
	if x != nil {
		return x.DisputeId
	}
	return ""
}

func (x *ResolveDisputeRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ResolveDisputeRequest) GetAdminNote() string {
	if x != nil {
		return x.AdminNote
	}
	return ""
}

type ResolveDisputeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dispute       *DisputePB             `protobuf:"bytes,1,opt,name=dispute,proto3" json:"dispute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveDisputeResponse) Reset() {
	*x = ResolveDisputeResponse{}
	mi := &file_dispute_v1_dispute_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveDisputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveDisputeResponse) ProtoMessage() {}

func (x *ResolveDisputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dispute_v1_dispute_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveDisputeResponse.ProtoReflect.Descriptor instead.
func (*ResolveDisputeResponse) Descriptor() ([]byte, []int) {
	return file_dispute_v1_dispute_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveDisputeResponse) GetDispute() *DisputePB {
	if x != nil {
		return x.Dispute
	}
	return nil
}

type GetDisputesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDisputesRequest) Reset() {
	*x = GetDisputesRequest{}
	mi := &file_dispute_v1_dispute_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDisputesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisputesRequest) ProtoMessage() {}

func (x *GetDisputesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dispute_v1_dispute_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisputesRequest.ProtoReflect.Descriptor instead.
func (*GetDisputesRequest) Descriptor() ([]byte, []int) {
	return file_dispute_v1_dispute_proto_rawDescGZIP(), []int{7}
}

func (x *GetDisputesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetDisputesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetDisputesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetDisputesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disputes      []*DisputePB           `protobuf:"bytes,1,rep,name=disputes,proto3" json:"disputes,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDisputesResponse) Reset() {
	*x = GetDisputesResponse{}
	mi := &file_dispute_v1_dispute_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDisputesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisputesResponse) ProtoMessage() {}

func (x *GetDisputesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dispute_v1_dispute_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisputesResponse.ProtoReflect.Descriptor instead.
func (*GetDisputesResponse) Descriptor() ([]byte, []int) {
	return file_dispute_v1_dispute_proto_rawDescGZIP(), []int{8}
}

func (x *GetDisputesResponse) GetDisputes() []*DisputePB {
	if x != nil {
		return x.Disputes
	}
	return nil
}

func (x *GetDisputesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetDisputeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisputeId     string                 `protobuf:"bytes,1,opt,name=dispute_id,json=disputeId,proto3" json:"dispute_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDisputeRequest) Reset() {
	*x = GetDisputeRequest{}
	mi := &file_dispute_v1_dispute_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDisputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisputeRequest) ProtoMessage() {}

func (x *GetDisputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dispute_v1_dispute_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisputeRequest.ProtoReflect.Descriptor instead.
func (*GetDisputeRequest) Descriptor() ([]byte, []int) {
	return file_dispute_v1_dispute_proto_rawDescGZIP(), []int{9}
}

func (x *GetDisputeRequest) GetDisputeId() string {
	if x != nil {
		return x.DisputeId
	}
	return ""
}

type GetDisputeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dispute       *DisputePB             `protobuf:"bytes,1,opt,name=dispute,proto3" json:"dispute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDisputeResponse) Reset() {
	*x = GetDisputeResponse{}
	mi := &file_dispute_v1_dispute_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDisputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisputeResponse) ProtoMessage() {}

func (x *GetDisputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dispute_v1_dispute_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisputeResponse.ProtoReflect.Descriptor instead.
func (*GetDisputeResponse) Descriptor() ([]byte, []int) {
	return file_dispute_v1_dispute_proto_rawDescGZIP(), []int{10}
}

func (x *GetDisputeResponse) GetDispute() *DisputePB {
	if x != nil {
		return x.Dispute
	}
	return nil
}

var File_dispute_v1_dispute_proto protoreflect.FileDescriptor

const file_dispute_v1_dispute_proto_rawDesc = "" +
	"\n" +
	"\x18dispute/v1/dispute.proto\x12\n" +
	"dispute.v1\x1a\x1cgoogle/api/annotations.proto\"\x87\x03\n" +
	"\tDisputePB\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12 \n" +
	"\fraised_by_id\x18\x03 \x01(\tR\n" +
	"raisedById\x12$\n" +
	"\x0eraised_by_name\x18\x04 \x01(\tR\fraisedByName\x12\x1d\n" +
	"\n" +
	"against_id\x18\x05 \x01(\tR\tagainstId\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12#\n" +
	"\revidence_urls\x18\b \x03(\tR\fevidenceUrls\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"admin_note\x18\n" +
	" \x01(\tR\tadminNote\x12\x16\n" +
	"\x06action\x18\v \x01(\tR\x06action\x12\x1f\n" +
	"\vresolved_at\x18\f \x01(\tR\n" +
	"resolvedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\"f\n" +
	"\x13RaiseDisputeRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"G\n" +
	"\x14RaiseDisputeResponse\x12/\n" +
	"\adispute\x18\x01 \x01(\v2\x15.dispute.v1.DisputePBR\adispute\"Q\n" +
	"\x15UploadEvidenceRequest\x12\x1d\n" +
	"\n" +
	"dispute_id\x18\x01 \x01(\tR\tdisputeId\x12\x19\n" +
	"\bfile_url\x18\x02 \x01(\tR\afileUrl\"I\n" +
	"\x16UploadEvidenceResponse\x12/\n" +
	"\adispute\x18\x01 \x01(\v2\x15.dispute.v1.DisputePBR\adispute\"m\n" +
	"\x15ResolveDisputeRequest\x12\x1d\n" +
	"\n" +
	"dispute_id\x18\x01 \x01(\tR\tdisputeId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"admin_note\x18\x03 \x01(\tR\tadminNote\"I\n" +
	"\x16ResolveDisputeResponse\x12/\n" +
	"\adispute\x18\x01 \x01(\v2\x15.dispute.v1.DisputePBR\adispute\"V\n" +
	"\x12GetDisputesRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"^\n" +
	"\x13GetDisputesResponse\x121\n" +
	"\bdisputes\x18\x01 \x03(\v2\x15.dispute.v1.DisputePBR\bdisputes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"2\n" +
	"\x11GetDisputeRequest\x12\x1d\n" +
	"\n" +
	"dispute_id\x18\x01 \x01(\tR\tdisputeId\"E\n" +
	"\x12GetDisputeResponse\x12/\n" +
	"\adispute\x18\x01 \x01(\v2\x15.dispute.v1.DisputePBR\adispute2\xe3\x04\n" +
	"\x0eDisputeService\x12j\n" +
	"\fRaiseDispute\x12\x1f.dispute.v1.RaiseDisputeRequest\x1a .dispute.v1.RaiseDisputeResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/disputes\x12\x86\x01\n" +
	"\x0eUploadEvidence\x12!.dispute.v1.UploadEvidenceRequest\x1a\".dispute.v1.UploadEvidenceResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/disputes/{dispute_id}/evidence\x12\x85\x01\n" +
	"\x0eResolveDispute\x12!.dispute.v1.ResolveDisputeRequest\x1a\".dispute.v1.ResolveDisputeResponse\",\x82\xd3\xe4\x93\x02&:\x01*2!/v1/disputes/{dispute_id}/resolve\x12d\n" +
	"\vGetDisputes\x12\x1e.dispute.v1.GetDisputesRequest\x1a\x1f.dispute.v1.GetDisputesResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/disputes\x12n\n" +
	"\n" +
	"GetDispute\x12\x1d.dispute.v1.GetDisputeRequest\x1a\x1e.dispute.v1.GetDisputeResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/disputes/{dispute_id}BSZQgithub.com/yourname/fixflow-backend/internal/adapter/grpc/pb/dispute/v1;disputev1b\x06proto3"

var (
	file_dispute_v1_dispute_proto_rawDescOnce sync.Once
	file_dispute_v1_dispute_proto_rawDescData []byte
)

func file_dispute_v1_dispute_proto_rawDescGZIP() []byte {
	file_dispute_v1_dispute_proto_rawDescOnce.Do(func() {
		file_dispute_v1_dispute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dispute_v1_dispute_proto_rawDesc), len(file_dispute_v1_dispute_proto_rawDesc)))
	})
	return file_dispute_v1_dispute_proto_rawDescData
}

var file_dispute_v1_dispute_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_dispute_v1_dispute_proto_goTypes = []any{
	(*DisputePB)(nil),              // 0: dispute.v1.DisputePB
	(*RaiseDisputeRequest)(nil),    // 1: dispute.v1.RaiseDisputeRequest
	(*RaiseDisputeResponse)(nil),   // 2: dispute.v1.RaiseDisputeResponse
	(*UploadEvidenceRequest)(nil),  // 3: dispute.v1.UploadEvidenceRequest
	(*UploadEvidenceResponse)(nil), // 4: dispute.v1.UploadEvidenceResponse
	(*ResolveDisputeRequest)(nil),  // 5: dispute.v1.ResolveDisputeRequest
	(*ResolveDisputeResponse)(nil), // 6: dispute.v1.ResolveDisputeResponse
	(*GetDisputesRequest)(nil),     // 7: dispute.v1.GetDisputesRequest
	(*GetDisputesResponse)(nil),    // 8: dispute.v1.GetDisputesResponse
	(*GetDisputeRequest)(nil),      // 9: dispute.v1.GetDisputeRequest
	(*GetDisputeResponse)(nil),     // 10: dispute.v1.GetDisputeResponse
}
var file_dispute_v1_dispute_proto_depIdxs = []int32{
	0,  // 0: dispute.v1.RaiseDisputeResponse.dispute:type_name -> dispute.v1.DisputePB
	0,  // 1: dispute.v1.UploadEvidenceResponse.dispute:type_name -> dispute.v1.DisputePB
	0,  // 2: dispute.v1.ResolveDisputeResponse.dispute:type_name -> dispute.v1.DisputePB
	0,  // 3: dispute.v1.GetDisputesResponse.disputes:type_name -> dispute.v1.DisputePB
	0,  // 4: dispute.v1.GetDisputeResponse.dispute:type_name -> dispute.v1.DisputePB
	1,  // 5: dispute.v1.DisputeService.RaiseDispute:input_type -> dispute.v1.RaiseDisputeRequest
	3,  // 6: dispute.v1.DisputeService.UploadEvidence:input_type -> dispute.v1.UploadEvidenceRequest
	5,  // 7: dispute.v1.DisputeService.ResolveDispute:input_type -> dispute.v1.ResolveDisputeRequest
	7,  // 8: dispute.v1.DisputeService.GetDisputes:input_type -> dispute.v1.GetDisputesRequest
	9,  // 9: dispute.v1.DisputeService.GetDispute:input_type -> dispute.v1.GetDisputeRequest
	2,  // 10: dispute.v1.DisputeService.RaiseDispute:output_type -> dispute.v1.RaiseDisputeResponse
	4,  // 11: dispute.v1.DisputeService.UploadEvidence:output_type -> dispute.v1.UploadEvidenceResponse
	6,  // 12: dispute.v1.DisputeService.ResolveDispute:output_type -> dispute.v1.ResolveDisputeResponse
	8,  // 13: dispute.v1.DisputeService.GetDisputes:output_type -> dispute.v1.GetDisputesResponse
	10, // 14: dispute.v1.DisputeService.GetDispute:output_type -> dispute.v1.GetDisputeResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_dispute_v1_dispute_proto_init() }
func file_dispute_v1_dispute_proto_init() {
	if File_dispute_v1_dispute_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dispute_v1_dispute_proto_rawDesc), len(file_dispute_v1_dispute_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dispute_v1_dispute_proto_goTypes,
		DependencyIndexes: file_dispute_v1_dispute_proto_depIdxs,
		MessageInfos:      file_dispute_v1_dispute_proto_msgTypes,
	}.Build()
	File_dispute_v1_dispute_proto = out.File
	file_dispute_v1_dispute_proto_goTypes = nil
	file_dispute_v1_dispute_proto_depIdxs = nil
}
