apiVersion: v1
kind: Service
metadata:
  name: fixflow-backend-service
  namespace: fixflow
spec:
  selector:
    app: fixflow-backend
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
