// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: job/v1/job.proto

package jobv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	TechnicianId  string                 `protobuf:"bytes,3,opt,name=technician_id,json=technicianId,proto3" json:"technician_id,omitempty"`
	ServiceType   string                 `protobuf:"bytes,4,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Latitude      float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Urgency       string                 `protobuf:"bytes,8,opt,name=urgency,proto3" json:"urgency,omitempty"`
	IsEmergency   bool                   `protobuf:"varint,9,opt,name=is_emergency,json=isEmergency,proto3" json:"is_emergency,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_job_v1_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Job) GetTechnicianId() string {
	if x != nil {
		return x.TechnicianId
	}
	return ""
}

func (x *Job) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *Job) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Job) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Job) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Job) GetUrgency() string {
	if x != nil {
		return x.Urgency
	}
	return ""
}

func (x *Job) GetIsEmergency() bool {
	if x != nil {
		return x.IsEmergency
	}
	return false
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Job) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ServiceType   string                 `protobuf:"bytes,2,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Lat           float64                `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,5,opt,name=lng,proto3" json:"lng,omitempty"`
	Urgency       string                 `protobuf:"bytes,6,opt,name=urgency,proto3" json:"urgency,omitempty"`
	IsEmergency   bool                   `protobuf:"varint,7,opt,name=is_emergency,json=isEmergency,proto3" json:"is_emergency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobRequest) Reset() {
	*x = CreateJobRequest{}
	mi := &file_job_v1_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobRequest) ProtoMessage() {}

func (x *CreateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobRequest.ProtoReflect.Descriptor instead.
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{1}
}

func (x *CreateJobRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateJobRequest) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *CreateJobRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateJobRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *CreateJobRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *CreateJobRequest) GetUrgency() string {
	if x != nil {
		return x.Urgency
	}
	return ""
}

func (x *CreateJobRequest) GetIsEmergency() bool {
	if x != nil {
		return x.IsEmergency
	}
	return false
}

type CreateJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobResponse) Reset() {
	*x = CreateJobResponse{}
	mi := &file_job_v1_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobResponse) ProtoMessage() {}

func (x *CreateJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobResponse.ProtoReflect.Descriptor instead.
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{2}
}

func (x *CreateJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_job_v1_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_job_v1_job_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{4}
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type UpdateJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	NewStatus     string                 `protobuf:"bytes,2,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	TechnicianId  string                 `protobuf:"bytes,3,opt,name=technician_id,json=technicianId,proto3" json:"technician_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobStatusRequest) Reset() {
	*x = UpdateJobStatusRequest{}
	mi := &file_job_v1_job_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobStatusRequest) ProtoMessage() {}

func (x *UpdateJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *UpdateJobStatusRequest) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

func (x *UpdateJobStatusRequest) GetTechnicianId() string {
	if x != nil {
		return x.TechnicianId
	}
	return ""
}

type UpdateJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobStatusResponse) Reset() {
	*x = UpdateJobStatusResponse{}
	mi := &file_job_v1_job_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobStatusResponse) ProtoMessage() {}

func (x *UpdateJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateJobStatusResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type ListCustomerJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomerJobsRequest) Reset() {
	*x = ListCustomerJobsRequest{}
	mi := &file_job_v1_job_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomerJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomerJobsRequest) ProtoMessage() {}

func (x *ListCustomerJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomerJobsRequest.ProtoReflect.Descriptor instead.
func (*ListCustomerJobsRequest) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{7}
}

func (x *ListCustomerJobsRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ListCustomerJobsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCustomerJobsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListCustomerJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomerJobsResponse) Reset() {
	*x = ListCustomerJobsResponse{}
	mi := &file_job_v1_job_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomerJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomerJobsResponse) ProtoMessage() {}

func (x *ListCustomerJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomerJobsResponse.ProtoReflect.Descriptor instead.
func (*ListCustomerJobsResponse) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{8}
}

func (x *ListCustomerJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListCustomerJobsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type StreamJobUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamJobUpdatesRequest) Reset() {
	*x = StreamJobUpdatesRequest{}
	mi := &file_job_v1_job_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamJobUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamJobUpdatesRequest) ProtoMessage() {}

func (x *StreamJobUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamJobUpdatesRequest.ProtoReflect.Descriptor instead.
func (*StreamJobUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{9}
}

func (x *StreamJobUpdatesRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobUpdateEvent) Reset() {
	*x = JobUpdateEvent{}
	mi := &file_job_v1_job_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobUpdateEvent) ProtoMessage() {}

func (x *JobUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobUpdateEvent.ProtoReflect.Descriptor instead.
func (*JobUpdateEvent) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{10}
}

func (x *JobUpdateEvent) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobUpdateEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobUpdateEvent) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_job_v1_job_proto protoreflect.FileDescriptor

const file_job_v1_job_proto_rawDesc = "" +
	"\n" +
	"\x10job/v1/job.proto\x12\x06job.v1\x1a\x1cgoogle/api/annotations.proto\"\xed\x02\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12#\n" +
	"\rtechnician_id\x18\x03 \x01(\tR\ftechnicianId\x12!\n" +
	"\fservice_type\x18\x04 \x01(\tR\vserviceType\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\x12\x18\n" +
	"\aurgency\x18\b \x01(\tR\aurgency\x12!\n" +
	"\fis_emergency\x18\t \x01(\bR\visEmergency\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"\xd9\x01\n" +
	"\x10CreateJobRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\fservice_type\x18\x02 \x01(\tR\vserviceType\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x05 \x01(\x01R\x03lng\x12\x18\n" +
	"\aurgency\x18\x06 \x01(\tR\aurgency\x12!\n" +
	"\fis_emergency\x18\a \x01(\bR\visEmergency\"2\n" +
	"\x11CreateJobResponse\x12\x1d\n" +
	"\x03job\x18\x01 \x01(\v2\v.job.v1.JobR\x03job\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"/\n" +
	"\x0eGetJobResponse\x12\x1d\n" +
	"\x03job\x18\x01 \x01(\v2\v.job.v1.JobR\x03job\"s\n" +
	"\x16UpdateJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"new_status\x18\x02 \x01(\tR\tnewStatus\x12#\n" +
	"\rtechnician_id\x18\x03 \x01(\tR\ftechnicianId\"8\n" +
	"\x17UpdateJobStatusResponse\x12\x1d\n" +
	"\x03job\x18\x01 \x01(\v2\v.job.v1.JobR\x03job\"k\n" +
	"\x17ListCustomerJobsRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"Q\n" +
	"\x18ListCustomerJobsResponse\x12\x1f\n" +
	"\x04jobs\x18\x01 \x03(\v2\v.job.v1.JobR\x04jobs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"0\n" +
	"\x17StreamJobUpdatesRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"^\n" +
	"\x0eJobUpdateEvent\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt2\xf8\x03\n" +
	"\n" +
	"JobService\x12Y\n" +
	"\tCreateJob\x12\x18.job.v1.CreateJobRequest\x1a\x19.job.v1.CreateJobResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/v1/jobs\x12V\n" +
	"\x06GetJob\x12\x15.job.v1.GetJobRequest\x1a\x16.job.v1.GetJobResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/jobs/{job_id}\x12{\n" +
	"\x0fUpdateJobStatus\x12\x1e.job.v1.UpdateJobStatusRequest\x1a\x1f.job.v1.UpdateJobStatusResponse\"'\x82\xd3\xe4\x93\x02!:\x01*2\x1c/api/v1/jobs/{job_id}/status\x12k\n" +
	"\x10ListCustomerJobs\x12\x1f.job.v1.ListCustomerJobsRequest\x1a .job.v1.ListCustomerJobsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/jobs\x12M\n" +
	"\x10StreamJobUpdates\x12\x1f.job.v1.StreamJobUpdatesRequest\x1a\x16.job.v1.JobUpdateEvent0\x01BKZIgithub.com/yourname/fixflow-backend/internal/adapter/grpc/pb/job/v1;jobv1b\x06proto3"

var (
	file_job_v1_job_proto_rawDescOnce sync.Once
	file_job_v1_job_proto_rawDescData []byte
)

func file_job_v1_job_proto_rawDescGZIP() []byte {
	file_job_v1_job_proto_rawDescOnce.Do(func() {
		file_job_v1_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_v1_job_proto_rawDesc), len(file_job_v1_job_proto_rawDesc)))
	})
	return file_job_v1_job_proto_rawDescData
}

var file_job_v1_job_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_job_v1_job_proto_goTypes = []any{
	(*Job)(nil),                      // 0: job.v1.Job
	(*CreateJobRequest)(nil),         // 1: job.v1.CreateJobRequest
	(*CreateJobResponse)(nil),        // 2: job.v1.CreateJobResponse
	(*GetJobRequest)(nil),            // 3: job.v1.GetJobRequest
	(*GetJobResponse)(nil),           // 4: job.v1.GetJobResponse
	(*UpdateJobStatusRequest)(nil),   // 5: job.v1.UpdateJobStatusRequest
	(*UpdateJobStatusResponse)(nil),  // 6: job.v1.UpdateJobStatusResponse
	(*ListCustomerJobsRequest)(nil),  // 7: job.v1.ListCustomerJobsRequest
	(*ListCustomerJobsResponse)(nil), // 8: job.v1.ListCustomerJobsResponse
	(*StreamJobUpdatesRequest)(nil),  // 9: job.v1.StreamJobUpdatesRequest
	(*JobUpdateEvent)(nil),           // 10: job.v1.JobUpdateEvent
}
var file_job_v1_job_proto_depIdxs = []int32{
	0,  // 0: job.v1.CreateJobResponse.job:type_name -> job.v1.Job
	0,  // 1: job.v1.GetJobResponse.job:type_name -> job.v1.Job
	0,  // 2: job.v1.UpdateJobStatusResponse.job:type_name -> job.v1.Job
	0,  // 3: job.v1.ListCustomerJobsResponse.jobs:type_name -> job.v1.Job
	1,  // 4: job.v1.JobService.CreateJob:input_type -> job.v1.CreateJobRequest
	3,  // 5: job.v1.JobService.GetJob:input_type -> job.v1.GetJobRequest
	5,  // 6: job.v1.JobService.UpdateJobStatus:input_type -> job.v1.UpdateJobStatusRequest
	7,  // 7: job.v1.JobService.ListCustomerJobs:input_type -> job.v1.ListCustomerJobsRequest
	9,  // 8: job.v1.JobService.StreamJobUpdates:input_type -> job.v1.StreamJobUpdatesRequest
	2,  // 9: job.v1.JobService.CreateJob:output_type -> job.v1.CreateJobResponse
	4,  // 10: job.v1.JobService.GetJob:output_type -> job.v1.GetJobResponse
	6,  // 11: job.v1.JobService.UpdateJobStatus:output_type -> job.v1.UpdateJobStatusResponse
	8,  // 12: job.v1.JobService.ListCustomerJobs:output_type -> job.v1.ListCustomerJobsResponse
	10, // 13: job.v1.JobService.StreamJobUpdates:output_type -> job.v1.JobUpdateEvent
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_job_v1_job_proto_init() }
func file_job_v1_job_proto_init() {
	if File_job_v1_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_v1_job_proto_rawDesc), len(file_job_v1_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_v1_job_proto_goTypes,
		DependencyIndexes: file_job_v1_job_proto_depIdxs,
		MessageInfos:      file_job_v1_job_proto_msgTypes,
	}.Build()
	File_job_v1_job_proto = out.File
	file_job_v1_job_proto_goTypes = nil
	file_job_v1_job_proto_depIdxs = nil
}
