// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: supplier/v1/supplier.proto

package supplierv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SupplierService_RegisterSupplier_FullMethodName    = "/supplier.v1.SupplierService/RegisterSupplier"
	SupplierService_GetProfile_FullMethodName          = "/supplier.v1.SupplierService/GetProfile"
	SupplierService_UpdateProfile_FullMethodName       = "/supplier.v1.SupplierService/UpdateProfile"
	SupplierService_GetNearbySuppliers_FullMethodName  = "/supplier.v1.SupplierService/GetNearbySuppliers"
	SupplierService_AddMaterial_FullMethodName         = "/supplier.v1.SupplierService/AddMaterial"
	SupplierService_UpdateMaterial_FullMethodName      = "/supplier.v1.SupplierService/UpdateMaterial"
	SupplierService_SoftDeleteMaterial_FullMethodName  = "/supplier.v1.SupplierService/SoftDeleteMaterial"
	SupplierService_ListMaterials_FullMethodName       = "/supplier.v1.SupplierService/ListMaterials"
	SupplierService_UpdateStock_FullMethodName         = "/supplier.v1.SupplierService/UpdateStock"
	SupplierService_BulkImportMaterials_FullMethodName = "/supplier.v1.SupplierService/BulkImportMaterials"
	SupplierService_RequestQuotation_FullMethodName    = "/supplier.v1.SupplierService/RequestQuotation"
	SupplierService_RespondToQuotation_FullMethodName  = "/supplier.v1.SupplierService/RespondToQuotation"
	SupplierService_CounterOffer_FullMethodName        = "/supplier.v1.SupplierService/CounterOffer"
	SupplierService_AcceptQuotation_FullMethodName     = "/supplier.v1.SupplierService/AcceptQuotation"
	SupplierService_RejectQuotation_FullMethodName     = "/supplier.v1.SupplierService/RejectQuotation"
	SupplierService_ListQuotations_FullMethodName      = "/supplier.v1.SupplierService/ListQuotations"
)

// SupplierServiceClient is the client API for SupplierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SupplierServiceClient interface {
	// Supplier profiles
	RegisterSupplier(ctx context.Context, in *RegisterSupplierRequest, opts ...grpc.CallOption) (*RegisterSupplierResponse, error)
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
	GetNearbySuppliers(ctx context.Context, in *GetNearbySuppliersRequest, opts ...grpc.CallOption) (*GetNearbySuppliersResponse, error)
	// Materials
	AddMaterial(ctx context.Context, in *AddMaterialRequest, opts ...grpc.CallOption) (*AddMaterialResponse, error)
	UpdateMaterial(ctx context.Context, in *UpdateMaterialRequest, opts ...grpc.CallOption) (*UpdateMaterialResponse, error)
	SoftDeleteMaterial(ctx context.Context, in *SoftDeleteMaterialRequest, opts ...grpc.CallOption) (*SoftDeleteMaterialResponse, error)
	ListMaterials(ctx context.Context, in *ListMaterialsRequest, opts ...grpc.CallOption) (*ListMaterialsResponse, error)
	UpdateStock(ctx context.Context, in *UpdateStockRequest, opts ...grpc.CallOption) (*UpdateStockResponse, error)
	BulkImportMaterials(ctx context.Context, in *BulkImportMaterialsRequest, opts ...grpc.CallOption) (*BulkImportMaterialsResponse, error)
	// Quotations
	RequestQuotation(ctx context.Context, in *RequestQuotationRequest, opts ...grpc.CallOption) (*RequestQuotationResponse, error)
	RespondToQuotation(ctx context.Context, in *RespondToQuotationRequest, opts ...grpc.CallOption) (*RespondToQuotationResponse, error)
	CounterOffer(ctx context.Context, in *CounterOfferRequest, opts ...grpc.CallOption) (*CounterOfferResponse, error)
	AcceptQuotation(ctx context.Context, in *AcceptQuotationRequest, opts ...grpc.CallOption) (*AcceptQuotationResponse, error)
	RejectQuotation(ctx context.Context, in *RejectQuotationRequest, opts ...grpc.CallOption) (*RejectQuotationResponse, error)
	ListQuotations(ctx context.Context, in *ListQuotationsRequest, opts ...grpc.CallOption) (*ListQuotationsResponse, error)
}

type supplierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSupplierServiceClient(cc grpc.ClientConnInterface) SupplierServiceClient {
	return &supplierServiceClient{cc}
}

func (c *supplierServiceClient) RegisterSupplier(ctx context.Context, in *RegisterSupplierRequest, opts ...grpc.CallOption) (*RegisterSupplierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterSupplierResponse)
	err := c.cc.Invoke(ctx, SupplierService_RegisterSupplier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, SupplierService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, SupplierService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) GetNearbySuppliers(ctx context.Context, in *GetNearbySuppliersRequest, opts ...grpc.CallOption) (*GetNearbySuppliersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNearbySuppliersResponse)
	err := c.cc.Invoke(ctx, SupplierService_GetNearbySuppliers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) AddMaterial(ctx context.Context, in *AddMaterialRequest, opts ...grpc.CallOption) (*AddMaterialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMaterialResponse)
	err := c.cc.Invoke(ctx, SupplierService_AddMaterial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) UpdateMaterial(ctx context.Context, in *UpdateMaterialRequest, opts ...grpc.CallOption) (*UpdateMaterialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMaterialResponse)
	err := c.cc.Invoke(ctx, SupplierService_UpdateMaterial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) SoftDeleteMaterial(ctx context.Context, in *SoftDeleteMaterialRequest, opts ...grpc.CallOption) (*SoftDeleteMaterialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SoftDeleteMaterialResponse)
	err := c.cc.Invoke(ctx, SupplierService_SoftDeleteMaterial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) ListMaterials(ctx context.Context, in *ListMaterialsRequest, opts ...grpc.CallOption) (*ListMaterialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMaterialsResponse)
	err := c.cc.Invoke(ctx, SupplierService_ListMaterials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) UpdateStock(ctx context.Context, in *UpdateStockRequest, opts ...grpc.CallOption) (*UpdateStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStockResponse)
	err := c.cc.Invoke(ctx, SupplierService_UpdateStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) BulkImportMaterials(ctx context.Context, in *BulkImportMaterialsRequest, opts ...grpc.CallOption) (*BulkImportMaterialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkImportMaterialsResponse)
	err := c.cc.Invoke(ctx, SupplierService_BulkImportMaterials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) RequestQuotation(ctx context.Context, in *RequestQuotationRequest, opts ...grpc.CallOption) (*RequestQuotationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestQuotationResponse)
	err := c.cc.Invoke(ctx, SupplierService_RequestQuotation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) RespondToQuotation(ctx context.Context, in *RespondToQuotationRequest, opts ...grpc.CallOption) (*RespondToQuotationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespondToQuotationResponse)
	err := c.cc.Invoke(ctx, SupplierService_RespondToQuotation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) CounterOffer(ctx context.Context, in *CounterOfferRequest, opts ...grpc.CallOption) (*CounterOfferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CounterOfferResponse)
	err := c.cc.Invoke(ctx, SupplierService_CounterOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) AcceptQuotation(ctx context.Context, in *AcceptQuotationRequest, opts ...grpc.CallOption) (*AcceptQuotationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptQuotationResponse)
	err := c.cc.Invoke(ctx, SupplierService_AcceptQuotation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) RejectQuotation(ctx context.Context, in *RejectQuotationRequest, opts ...grpc.CallOption) (*RejectQuotationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectQuotationResponse)
	err := c.cc.Invoke(ctx, SupplierService_RejectQuotation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supplierServiceClient) ListQuotations(ctx context.Context, in *ListQuotationsRequest, opts ...grpc.CallOption) (*ListQuotationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListQuotationsResponse)
	err := c.cc.Invoke(ctx, SupplierService_ListQuotations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupplierServiceServer is the server API for SupplierService service.
// All implementations must embed UnimplementedSupplierServiceServer
// for forward compatibility.
type SupplierServiceServer interface {
	// Supplier profiles
	RegisterSupplier(context.Context, *RegisterSupplierRequest) (*RegisterSupplierResponse, error)
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	GetNearbySuppliers(context.Context, *GetNearbySuppliersRequest) (*GetNearbySuppliersResponse, error)
	// Materials
	AddMaterial(context.Context, *AddMaterialRequest) (*AddMaterialResponse, error)
	UpdateMaterial(context.Context, *UpdateMaterialRequest) (*UpdateMaterialResponse, error)
	SoftDeleteMaterial(context.Context, *SoftDeleteMaterialRequest) (*SoftDeleteMaterialResponse, error)
	ListMaterials(context.Context, *ListMaterialsRequest) (*ListMaterialsResponse, error)
	UpdateStock(context.Context, *UpdateStockRequest) (*UpdateStockResponse, error)
	BulkImportMaterials(context.Context, *BulkImportMaterialsRequest) (*BulkImportMaterialsResponse, error)
	// Quotations
	RequestQuotation(context.Context, *RequestQuotationRequest) (*RequestQuotationResponse, error)
	RespondToQuotation(context.Context, *RespondToQuotationRequest) (*RespondToQuotationResponse, error)
	CounterOffer(context.Context, *CounterOfferRequest) (*CounterOfferResponse, error)
	AcceptQuotation(context.Context, *AcceptQuotationRequest) (*AcceptQuotationResponse, error)
	RejectQuotation(context.Context, *RejectQuotationRequest) (*RejectQuotationResponse, error)
	ListQuotations(context.Context, *ListQuotationsRequest) (*ListQuotationsResponse, error)
	mustEmbedUnimplementedSupplierServiceServer()
}

// UnimplementedSupplierServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSupplierServiceServer struct{}

func (UnimplementedSupplierServiceServer) RegisterSupplier(context.Context, *RegisterSupplierRequest) (*RegisterSupplierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterSupplier not implemented")
}
func (UnimplementedSupplierServiceServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedSupplierServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedSupplierServiceServer) GetNearbySuppliers(context.Context, *GetNearbySuppliersRequest) (*GetNearbySuppliersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNearbySuppliers not implemented")
}
func (UnimplementedSupplierServiceServer) AddMaterial(context.Context, *AddMaterialRequest) (*AddMaterialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMaterial not implemented")
}
func (UnimplementedSupplierServiceServer) UpdateMaterial(context.Context, *UpdateMaterialRequest) (*UpdateMaterialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMaterial not implemented")
}
func (UnimplementedSupplierServiceServer) SoftDeleteMaterial(context.Context, *SoftDeleteMaterialRequest) (*SoftDeleteMaterialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SoftDeleteMaterial not implemented")
}
func (UnimplementedSupplierServiceServer) ListMaterials(context.Context, *ListMaterialsRequest) (*ListMaterialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMaterials not implemented")
}
func (UnimplementedSupplierServiceServer) UpdateStock(context.Context, *UpdateStockRequest) (*UpdateStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStock not implemented")
}
func (UnimplementedSupplierServiceServer) BulkImportMaterials(context.Context, *BulkImportMaterialsRequest) (*BulkImportMaterialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BulkImportMaterials not implemented")
}
func (UnimplementedSupplierServiceServer) RequestQuotation(context.Context, *RequestQuotationRequest) (*RequestQuotationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestQuotation not implemented")
}
func (UnimplementedSupplierServiceServer) RespondToQuotation(context.Context, *RespondToQuotationRequest) (*RespondToQuotationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RespondToQuotation not implemented")
}
func (UnimplementedSupplierServiceServer) CounterOffer(context.Context, *CounterOfferRequest) (*CounterOfferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CounterOffer not implemented")
}
func (UnimplementedSupplierServiceServer) AcceptQuotation(context.Context, *AcceptQuotationRequest) (*AcceptQuotationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptQuotation not implemented")
}
func (UnimplementedSupplierServiceServer) RejectQuotation(context.Context, *RejectQuotationRequest) (*RejectQuotationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectQuotation not implemented")
}
func (UnimplementedSupplierServiceServer) ListQuotations(context.Context, *ListQuotationsRequest) (*ListQuotationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListQuotations not implemented")
}
func (UnimplementedSupplierServiceServer) mustEmbedUnimplementedSupplierServiceServer() {}
func (UnimplementedSupplierServiceServer) testEmbeddedByValue()                         {}

// UnsafeSupplierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SupplierServiceServer will
// result in compilation errors.
type UnsafeSupplierServiceServer interface {
	mustEmbedUnimplementedSupplierServiceServer()
}

func RegisterSupplierServiceServer(s grpc.ServiceRegistrar, srv SupplierServiceServer) {
	// If the following call panics, it indicates UnimplementedSupplierServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SupplierService_ServiceDesc, srv)
}

func _SupplierService_RegisterSupplier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSupplierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).RegisterSupplier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierService_RegisterSupplier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).RegisterSupplier(ctx, req.(*RegisterSupplierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_GetNearbySuppliers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNearbySuppliersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).GetNearbySuppliers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierService_GetNearbySuppliers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).GetNearbySuppliers(ctx, req.(*GetNearbySuppliersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_AddMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).AddMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierService_AddMaterial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).AddMaterial(ctx, req.(*AddMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_UpdateMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).UpdateMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierService_UpdateMaterial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).UpdateMaterial(ctx, req.(*UpdateMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_SoftDeleteMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SoftDeleteMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).SoftDeleteMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierService_SoftDeleteMaterial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).SoftDeleteMaterial(ctx, req.(*SoftDeleteMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_ListMaterials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMaterialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).ListMaterials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierService_ListMaterials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).ListMaterials(ctx, req.(*ListMaterialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_UpdateStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).UpdateStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierService_UpdateStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).UpdateStock(ctx, req.(*UpdateStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_BulkImportMaterials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkImportMaterialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).BulkImportMaterials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierService_BulkImportMaterials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).BulkImportMaterials(ctx, req.(*BulkImportMaterialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_RequestQuotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestQuotationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).RequestQuotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierService_RequestQuotation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).RequestQuotation(ctx, req.(*RequestQuotationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_RespondToQuotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RespondToQuotationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).RespondToQuotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierService_RespondToQuotation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).RespondToQuotation(ctx, req.(*RespondToQuotationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_CounterOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CounterOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).CounterOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierService_CounterOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).CounterOffer(ctx, req.(*CounterOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_AcceptQuotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptQuotationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).AcceptQuotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierService_AcceptQuotation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).AcceptQuotation(ctx, req.(*AcceptQuotationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_RejectQuotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectQuotationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).RejectQuotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierService_RejectQuotation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).RejectQuotation(ctx, req.(*RejectQuotationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupplierService_ListQuotations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQuotationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupplierServiceServer).ListQuotations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupplierService_ListQuotations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupplierServiceServer).ListQuotations(ctx, req.(*ListQuotationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SupplierService_ServiceDesc is the grpc.ServiceDesc for SupplierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SupplierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "supplier.v1.SupplierService",
	HandlerType: (*SupplierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSupplier",
			Handler:    _SupplierService_RegisterSupplier_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _SupplierService_GetProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _SupplierService_UpdateProfile_Handler,
		},
		{
			MethodName: "GetNearbySuppliers",
			Handler:    _SupplierService_GetNearbySuppliers_Handler,
		},
		{
			MethodName: "AddMaterial",
			Handler:    _SupplierService_AddMaterial_Handler,
		},
		{
			MethodName: "UpdateMaterial",
			Handler:    _SupplierService_UpdateMaterial_Handler,
		},
		{
			MethodName: "SoftDeleteMaterial",
			Handler:    _SupplierService_SoftDeleteMaterial_Handler,
		},
		{
			MethodName: "ListMaterials",
			Handler:    _SupplierService_ListMaterials_Handler,
		},
		{
			MethodName: "UpdateStock",
			Handler:    _SupplierService_UpdateStock_Handler,
		},
		{
			MethodName: "BulkImportMaterials",
			Handler:    _SupplierService_BulkImportMaterials_Handler,
		},
		{
			MethodName: "RequestQuotation",
			Handler:    _SupplierService_RequestQuotation_Handler,
		},
		{
			MethodName: "RespondToQuotation",
			Handler:    _SupplierService_RespondToQuotation_Handler,
		},
		{
			MethodName: "CounterOffer",
			Handler:    _SupplierService_CounterOffer_Handler,
		},
		{
			MethodName: "AcceptQuotation",
			Handler:    _SupplierService_AcceptQuotation_Handler,
		},
		{
			MethodName: "RejectQuotation",
			Handler:    _SupplierService_RejectQuotation_Handler,
		},
		{
			MethodName: "ListQuotations",
			Handler:    _SupplierService_ListQuotations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "supplier/v1/supplier.proto",
}
