// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: supplier/v1/supplier.proto

package supplierv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Supplier struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BusinessName    string                 `protobuf:"bytes,3,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	ContactPhone    string                 `protobuf:"bytes,4,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	ContactEmail    string                 `protobuf:"bytes,5,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	Lat             float64                `protobuf:"fixed64,6,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng             float64                `protobuf:"fixed64,7,opt,name=lng,proto3" json:"lng,omitempty"`
	ServiceRadiusKm float64                `protobuf:"fixed64,8,opt,name=service_radius_km,json=serviceRadiusKm,proto3" json:"service_radius_km,omitempty"`
	Rating          float64                `protobuf:"fixed64,9,opt,name=rating,proto3" json:"rating,omitempty"`
	ReviewCount     int32                  `protobuf:"varint,10,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	IsVerified      bool                   `protobuf:"varint,11,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Supplier) Reset() {
	*x = Supplier{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Supplier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Supplier) ProtoMessage() {}

func (x *Supplier) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Supplier.ProtoReflect.Descriptor instead.
func (*Supplier) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{0}
}

func (x *Supplier) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Supplier) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Supplier) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

func (x *Supplier) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *Supplier) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *Supplier) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Supplier) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Supplier) GetServiceRadiusKm() float64 {
	if x != nil {
		return x.ServiceRadiusKm
	}
	return 0
}

func (x *Supplier) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Supplier) GetReviewCount() int32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

func (x *Supplier) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *Supplier) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Material struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SupplierId    string                 `protobuf:"bytes,2,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,7,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,9,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,10,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Material) Reset() {
	*x = Material{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Material) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Material) ProtoMessage() {}

func (x *Material) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Material.ProtoReflect.Descriptor instead.
func (*Material) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{1}
}

func (x *Material) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Material) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *Material) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Material) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Material) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Material) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Material) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *Material) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Material) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Material) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *Material) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Material) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Quotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MaterialId    string                 `protobuf:"bytes,2,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	MaterialName  string                 `protobuf:"bytes,3,opt,name=material_name,json=materialName,proto3" json:"material_name,omitempty"`
	JobId         string                 `protobuf:"bytes,4,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	RequesterId   string                 `protobuf:"bytes,5,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	SupplierId    string                 `protobuf:"bytes,6,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	RequestedQty  int32                  `protobuf:"varint,8,opt,name=requested_qty,json=requestedQty,proto3" json:"requested_qty,omitempty"`
	Notes         string                 `protobuf:"bytes,9,opt,name=notes,proto3" json:"notes,omitempty"`
	OfferedPrice  float64                `protobuf:"fixed64,10,opt,name=offered_price,json=offeredPrice,proto3" json:"offered_price,omitempty"`
	CounterPrice  float64                `protobuf:"fixed64,11,opt,name=counter_price,json=counterPrice,proto3" json:"counter_price,omitempty"`
	AvailableQty  int32                  `protobuf:"varint,12,opt,name=available_qty,json=availableQty,proto3" json:"available_qty,omitempty"`
	DeliveryDate  string                 `protobuf:"bytes,13,opt,name=delivery_date,json=deliveryDate,proto3" json:"delivery_date,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,14,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RequestedAt   string                 `protobuf:"bytes,15,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	RespondedAt   string                 `protobuf:"bytes,16,opt,name=responded_at,json=respondedAt,proto3" json:"responded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quotation) Reset() {
	*x = Quotation{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quotation) ProtoMessage() {}

func (x *Quotation) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quotation.ProtoReflect.Descriptor instead.
func (*Quotation) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{2}
}

func (x *Quotation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Quotation) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

func (x *Quotation) GetMaterialName() string {
	if x != nil {
		return x.MaterialName
	}
	return ""
}

func (x *Quotation) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Quotation) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *Quotation) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *Quotation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Quotation) GetRequestedQty() int32 {
	if x != nil {
		return x.RequestedQty
	}
	return 0
}

func (x *Quotation) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Quotation) GetOfferedPrice() float64 {
	if x != nil {
		return x.OfferedPrice
	}
	return 0
}

func (x *Quotation) GetCounterPrice() float64 {
	if x != nil {
		return x.CounterPrice
	}
	return 0
}

func (x *Quotation) GetAvailableQty() int32 {
	if x != nil {
		return x.AvailableQty
	}
	return 0
}

func (x *Quotation) GetDeliveryDate() string {
	if x != nil {
		return x.DeliveryDate
	}
	return ""
}

func (x *Quotation) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *Quotation) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

func (x *Quotation) GetRespondedAt() string {
	if x != nil {
		return x.RespondedAt
	}
	return ""
}

type RegisterSupplierRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BusinessName    string                 `protobuf:"bytes,1,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	ContactPhone    string                 `protobuf:"bytes,2,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	ContactEmail    string                 `protobuf:"bytes,3,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	Lat             float64                `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng             float64                `protobuf:"fixed64,5,opt,name=lng,proto3" json:"lng,omitempty"`
	ServiceRadiusKm float64                `protobuf:"fixed64,6,opt,name=service_radius_km,json=serviceRadiusKm,proto3" json:"service_radius_km,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterSupplierRequest) Reset() {
	*x = RegisterSupplierRequest{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSupplierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSupplierRequest) ProtoMessage() {}

func (x *RegisterSupplierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSupplierRequest.ProtoReflect.Descriptor instead.
func (*RegisterSupplierRequest) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterSupplierRequest) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

func (x *RegisterSupplierRequest) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *RegisterSupplierRequest) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *RegisterSupplierRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *RegisterSupplierRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *RegisterSupplierRequest) GetServiceRadiusKm() float64 {
	if x != nil {
		return x.ServiceRadiusKm
	}
	return 0
}

type RegisterSupplierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supplier      *Supplier              `protobuf:"bytes,1,opt,name=supplier,proto3" json:"supplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSupplierResponse) Reset() {
	*x = RegisterSupplierResponse{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSupplierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSupplierResponse) ProtoMessage() {}

func (x *RegisterSupplierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSupplierResponse.ProtoReflect.Descriptor instead.
func (*RegisterSupplierResponse) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterSupplierResponse) GetSupplier() *Supplier {
	if x != nil {
		return x.Supplier
	}
	return nil
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SupplierId    string                 `protobuf:"bytes,1,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"` // optional
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{5}
}

func (x *GetProfileRequest) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supplier      *Supplier              `protobuf:"bytes,1,opt,name=supplier,proto3" json:"supplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{6}
}

func (x *GetProfileResponse) GetSupplier() *Supplier {
	if x != nil {
		return x.Supplier
	}
	return nil
}

type UpdateProfileRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BusinessName    string                 `protobuf:"bytes,1,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	ContactPhone    string                 `protobuf:"bytes,2,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	ContactEmail    string                 `protobuf:"bytes,3,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	Lat             float64                `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng             float64                `protobuf:"fixed64,5,opt,name=lng,proto3" json:"lng,omitempty"`
	ServiceRadiusKm float64                `protobuf:"fixed64,6,opt,name=service_radius_km,json=serviceRadiusKm,proto3" json:"service_radius_km,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProfileRequest) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

func (x *UpdateProfileRequest) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *UpdateProfileRequest) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *UpdateProfileRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *UpdateProfileRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *UpdateProfileRequest) GetServiceRadiusKm() float64 {
	if x != nil {
		return x.ServiceRadiusKm
	}
	return 0
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supplier      *Supplier              `protobuf:"bytes,1,opt,name=supplier,proto3" json:"supplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProfileResponse) GetSupplier() *Supplier {
	if x != nil {
		return x.Supplier
	}
	return nil
}

type GetNearbySuppliersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,3,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNearbySuppliersRequest) Reset() {
	*x = GetNearbySuppliersRequest{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNearbySuppliersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearbySuppliersRequest) ProtoMessage() {}

func (x *GetNearbySuppliersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearbySuppliersRequest.ProtoReflect.Descriptor instead.
func (*GetNearbySuppliersRequest) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{9}
}

func (x *GetNearbySuppliersRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GetNearbySuppliersRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *GetNearbySuppliersRequest) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

func (x *GetNearbySuppliersRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GetNearbySuppliersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suppliers     []*Supplier            `protobuf:"bytes,1,rep,name=suppliers,proto3" json:"suppliers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNearbySuppliersResponse) Reset() {
	*x = GetNearbySuppliersResponse{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNearbySuppliersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNearbySuppliersResponse) ProtoMessage() {}

func (x *GetNearbySuppliersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNearbySuppliersResponse.ProtoReflect.Descriptor instead.
func (*GetNearbySuppliersResponse) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{10}
}

func (x *GetNearbySuppliersResponse) GetSuppliers() []*Supplier {
	if x != nil {
		return x.Suppliers
	}
	return nil
}

type AddMaterialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,7,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMaterialRequest) Reset() {
	*x = AddMaterialRequest{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMaterialRequest) ProtoMessage() {}

func (x *AddMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMaterialRequest.ProtoReflect.Descriptor instead.
func (*AddMaterialRequest) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{11}
}

func (x *AddMaterialRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddMaterialRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AddMaterialRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddMaterialRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *AddMaterialRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddMaterialRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *AddMaterialRequest) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type AddMaterialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Material      *Material              `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMaterialResponse) Reset() {
	*x = AddMaterialResponse{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMaterialResponse) ProtoMessage() {}

func (x *AddMaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMaterialResponse.ProtoReflect.Descriptor instead.
func (*AddMaterialResponse) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{12}
}

func (x *AddMaterialResponse) GetMaterial() *Material {
	if x != nil {
		return x.Material
	}
	return nil
}

type UpdateMaterialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    string                 `protobuf:"bytes,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,8,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMaterialRequest) Reset() {
	*x = UpdateMaterialRequest{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMaterialRequest) ProtoMessage() {}

func (x *UpdateMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMaterialRequest.ProtoReflect.Descriptor instead.
func (*UpdateMaterialRequest) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateMaterialRequest) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

func (x *UpdateMaterialRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMaterialRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateMaterialRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateMaterialRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateMaterialRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateMaterialRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *UpdateMaterialRequest) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type UpdateMaterialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Material      *Material              `protobuf:"bytes,1,opt,name=material,proto3" json:"material,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMaterialResponse) Reset() {
	*x = UpdateMaterialResponse{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMaterialResponse) ProtoMessage() {}

func (x *UpdateMaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMaterialResponse.ProtoReflect.Descriptor instead.
func (*UpdateMaterialResponse) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateMaterialResponse) GetMaterial() *Material {
	if x != nil {
		return x.Material
	}
	return nil
}

type SoftDeleteMaterialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    string                 `protobuf:"bytes,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoftDeleteMaterialRequest) Reset() {
	*x = SoftDeleteMaterialRequest{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftDeleteMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftDeleteMaterialRequest) ProtoMessage() {}

func (x *SoftDeleteMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftDeleteMaterialRequest.ProtoReflect.Descriptor instead.
func (*SoftDeleteMaterialRequest) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{15}
}

func (x *SoftDeleteMaterialRequest) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

type SoftDeleteMaterialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoftDeleteMaterialResponse) Reset() {
	*x = SoftDeleteMaterialResponse{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftDeleteMaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftDeleteMaterialResponse) ProtoMessage() {}

func (x *SoftDeleteMaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftDeleteMaterialResponse.ProtoReflect.Descriptor instead.
func (*SoftDeleteMaterialResponse) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{16}
}

func (x *SoftDeleteMaterialResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListMaterialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SupplierId    string                 `protobuf:"bytes,1,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"` // optional
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMaterialsRequest) Reset() {
	*x = ListMaterialsRequest{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMaterialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMaterialsRequest) ProtoMessage() {}

func (x *ListMaterialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMaterialsRequest.ProtoReflect.Descriptor instead.
func (*ListMaterialsRequest) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{17}
}

func (x *ListMaterialsRequest) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *ListMaterialsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListMaterialsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMaterialsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMaterialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Materials     []*Material            `protobuf:"bytes,1,rep,name=materials,proto3" json:"materials,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMaterialsResponse) Reset() {
	*x = ListMaterialsResponse{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMaterialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMaterialsResponse) ProtoMessage() {}

func (x *ListMaterialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMaterialsResponse.ProtoReflect.Descriptor instead.
func (*ListMaterialsResponse) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{18}
}

func (x *ListMaterialsResponse) GetMaterials() []*Material {
	if x != nil {
		return x.Materials
	}
	return nil
}

func (x *ListMaterialsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UpdateStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    string                 `protobuf:"bytes,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	Delta         int32                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockRequest) Reset() {
	*x = UpdateStockRequest{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockRequest) ProtoMessage() {}

func (x *UpdateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockRequest) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateStockRequest) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

func (x *UpdateStockRequest) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type UpdateStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewStock      int32                  `protobuf:"varint,1,opt,name=new_stock,json=newStock,proto3" json:"new_stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockResponse) Reset() {
	*x = UpdateStockResponse{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockResponse) ProtoMessage() {}

func (x *UpdateStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockResponse.ProtoReflect.Descriptor instead.
func (*UpdateStockResponse) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateStockResponse) GetNewStock() int32 {
	if x != nil {
		return x.NewStock
	}
	return 0
}

type MaterialImportItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterialImportItem) Reset() {
	*x = MaterialImportItem{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterialImportItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialImportItem) ProtoMessage() {}

func (x *MaterialImportItem) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialImportItem.ProtoReflect.Descriptor instead.
func (*MaterialImportItem) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{21}
}

func (x *MaterialImportItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MaterialImportItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MaterialImportItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MaterialImportItem) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *MaterialImportItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MaterialImportItem) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type BulkImportMaterialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Materials     []*MaterialImportItem  `protobuf:"bytes,1,rep,name=materials,proto3" json:"materials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkImportMaterialsRequest) Reset() {
	*x = BulkImportMaterialsRequest{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkImportMaterialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkImportMaterialsRequest) ProtoMessage() {}

func (x *BulkImportMaterialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkImportMaterialsRequest.ProtoReflect.Descriptor instead.
func (*BulkImportMaterialsRequest) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{22}
}

func (x *BulkImportMaterialsRequest) GetMaterials() []*MaterialImportItem {
	if x != nil {
		return x.Materials
	}
	return nil
}

type BulkImportMaterialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImportedCount int32                  `protobuf:"varint,1,opt,name=imported_count,json=importedCount,proto3" json:"imported_count,omitempty"`
	FailedCount   int32                  `protobuf:"varint,2,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkImportMaterialsResponse) Reset() {
	*x = BulkImportMaterialsResponse{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkImportMaterialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkImportMaterialsResponse) ProtoMessage() {}

func (x *BulkImportMaterialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkImportMaterialsResponse.ProtoReflect.Descriptor instead.
func (*BulkImportMaterialsResponse) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{23}
}

func (x *BulkImportMaterialsResponse) GetImportedCount() int32 {
	if x != nil {
		return x.ImportedCount
	}
	return 0
}

func (x *BulkImportMaterialsResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *BulkImportMaterialsResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type RequestQuotationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    string                 `protobuf:"bytes,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // optional
	RequestedQty  int32                  `protobuf:"varint,3,opt,name=requested_qty,json=requestedQty,proto3" json:"requested_qty,omitempty"`
	Notes         string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestQuotationRequest) Reset() {
	*x = RequestQuotationRequest{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestQuotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestQuotationRequest) ProtoMessage() {}

func (x *RequestQuotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestQuotationRequest.ProtoReflect.Descriptor instead.
func (*RequestQuotationRequest) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{24}
}

func (x *RequestQuotationRequest) GetMaterialId() string {
	if x != nil {
		return x.MaterialId
	}
	return ""
}

func (x *RequestQuotationRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RequestQuotationRequest) GetRequestedQty() int32 {
	if x != nil {
		return x.RequestedQty
	}
	return 0
}

func (x *RequestQuotationRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type RequestQuotationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quotation     *Quotation             `protobuf:"bytes,1,opt,name=quotation,proto3" json:"quotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestQuotationResponse) Reset() {
	*x = RequestQuotationResponse{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestQuotationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestQuotationResponse) ProtoMessage() {}

func (x *RequestQuotationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestQuotationResponse.ProtoReflect.Descriptor instead.
func (*RequestQuotationResponse) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{25}
}

func (x *RequestQuotationResponse) GetQuotation() *Quotation {
	if x != nil {
		return x.Quotation
	}
	return nil
}

type RespondToQuotationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuotationId   string                 `protobuf:"bytes,1,opt,name=quotation_id,json=quotationId,proto3" json:"quotation_id,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Qty           int32                  `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
	DeliveryDate  string                 `protobuf:"bytes,4,opt,name=delivery_date,json=deliveryDate,proto3" json:"delivery_date,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondToQuotationRequest) Reset() {
	*x = RespondToQuotationRequest{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondToQuotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondToQuotationRequest) ProtoMessage() {}

func (x *RespondToQuotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondToQuotationRequest.ProtoReflect.Descriptor instead.
func (*RespondToQuotationRequest) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{26}
}

func (x *RespondToQuotationRequest) GetQuotationId() string {
	if x != nil {
		return x.QuotationId
	}
	return ""
}

func (x *RespondToQuotationRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *RespondToQuotationRequest) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *RespondToQuotationRequest) GetDeliveryDate() string {
	if x != nil {
		return x.DeliveryDate
	}
	return ""
}

type RespondToQuotationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quotation     *Quotation             `protobuf:"bytes,1,opt,name=quotation,proto3" json:"quotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondToQuotationResponse) Reset() {
	*x = RespondToQuotationResponse{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondToQuotationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondToQuotationResponse) ProtoMessage() {}

func (x *RespondToQuotationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondToQuotationResponse.ProtoReflect.Descriptor instead.
func (*RespondToQuotationResponse) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{27}
}

func (x *RespondToQuotationResponse) GetQuotation() *Quotation {
	if x != nil {
		return x.Quotation
	}
	return nil
}

type CounterOfferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuotationId   string                 `protobuf:"bytes,1,opt,name=quotation_id,json=quotationId,proto3" json:"quotation_id,omitempty"`
	CounterPrice  float64                `protobuf:"fixed64,2,opt,name=counter_price,json=counterPrice,proto3" json:"counter_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterOfferRequest) Reset() {
	*x = CounterOfferRequest{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterOfferRequest) ProtoMessage() {}

func (x *CounterOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterOfferRequest.ProtoReflect.Descriptor instead.
func (*CounterOfferRequest) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{28}
}

func (x *CounterOfferRequest) GetQuotationId() string {
	if x != nil {
		return x.QuotationId
	}
	return ""
}

func (x *CounterOfferRequest) GetCounterPrice() float64 {
	if x != nil {
		return x.CounterPrice
	}
	return 0
}

type CounterOfferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quotation     *Quotation             `protobuf:"bytes,1,opt,name=quotation,proto3" json:"quotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterOfferResponse) Reset() {
	*x = CounterOfferResponse{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterOfferResponse) ProtoMessage() {}

func (x *CounterOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterOfferResponse.ProtoReflect.Descriptor instead.
func (*CounterOfferResponse) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{29}
}

func (x *CounterOfferResponse) GetQuotation() *Quotation {
	if x != nil {
		return x.Quotation
	}
	return nil
}

type AcceptQuotationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuotationId   string                 `protobuf:"bytes,1,opt,name=quotation_id,json=quotationId,proto3" json:"quotation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptQuotationRequest) Reset() {
	*x = AcceptQuotationRequest{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptQuotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptQuotationRequest) ProtoMessage() {}

func (x *AcceptQuotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptQuotationRequest.ProtoReflect.Descriptor instead.
func (*AcceptQuotationRequest) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{30}
}

func (x *AcceptQuotationRequest) GetQuotationId() string {
	if x != nil {
		return x.QuotationId
	}
	return ""
}

type AcceptQuotationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quotation     *Quotation             `protobuf:"bytes,1,opt,name=quotation,proto3" json:"quotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptQuotationResponse) Reset() {
	*x = AcceptQuotationResponse{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptQuotationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptQuotationResponse) ProtoMessage() {}

func (x *AcceptQuotationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptQuotationResponse.ProtoReflect.Descriptor instead.
func (*AcceptQuotationResponse) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{31}
}

func (x *AcceptQuotationResponse) GetQuotation() *Quotation {
	if x != nil {
		return x.Quotation
	}
	return nil
}

type RejectQuotationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuotationId   string                 `protobuf:"bytes,1,opt,name=quotation_id,json=quotationId,proto3" json:"quotation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectQuotationRequest) Reset() {
	*x = RejectQuotationRequest{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectQuotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectQuotationRequest) ProtoMessage() {}

func (x *RejectQuotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectQuotationRequest.ProtoReflect.Descriptor instead.
func (*RejectQuotationRequest) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{32}
}

func (x *RejectQuotationRequest) GetQuotationId() string {
	if x != nil {
		return x.QuotationId
	}
	return ""
}

type RejectQuotationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectQuotationResponse) Reset() {
	*x = RejectQuotationResponse{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectQuotationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectQuotationResponse) ProtoMessage() {}

func (x *RejectQuotationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectQuotationResponse.ProtoReflect.Descriptor instead.
func (*RejectQuotationResponse) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{33}
}

func (x *RejectQuotationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListQuotationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SupplierId    string                 `protobuf:"bytes,1,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`    // optional
	RequesterId   string                 `protobuf:"bytes,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"` // optional
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                              // optional
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuotationsRequest) Reset() {
	*x = ListQuotationsRequest{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuotationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuotationsRequest) ProtoMessage() {}

func (x *ListQuotationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuotationsRequest.ProtoReflect.Descriptor instead.
func (*ListQuotationsRequest) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{34}
}

func (x *ListQuotationsRequest) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *ListQuotationsRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *ListQuotationsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListQuotationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListQuotationsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListQuotationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quotations    []*Quotation           `protobuf:"bytes,1,rep,name=quotations,proto3" json:"quotations,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuotationsResponse) Reset() {
	*x = ListQuotationsResponse{}
	mi := &file_supplier_v1_supplier_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuotationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuotationsResponse) ProtoMessage() {}

func (x *ListQuotationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_supplier_v1_supplier_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuotationsResponse.ProtoReflect.Descriptor instead.
func (*ListQuotationsResponse) Descriptor() ([]byte, []int) {
	return file_supplier_v1_supplier_proto_rawDescGZIP(), []int{35}
}

func (x *ListQuotationsResponse) GetQuotations() []*Quotation {
	if x != nil {
		return x.Quotations
	}
	return nil
}

func (x *ListQuotationsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_supplier_v1_supplier_proto protoreflect.FileDescriptor

const file_supplier_v1_supplier_proto_rawDesc = "" +
	"\n" +
	"\x1asupplier/v1/supplier.proto\x12\vsupplier.v1\"\xed\x02\n" +
	"\bSupplier\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rbusiness_name\x18\x03 \x01(\tR\fbusinessName\x12#\n" +
	"\rcontact_phone\x18\x04 \x01(\tR\fcontactPhone\x12#\n" +
	"\rcontact_email\x18\x05 \x01(\tR\fcontactEmail\x12\x10\n" +
	"\x03lat\x18\x06 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\a \x01(\x01R\x03lng\x12*\n" +
	"\x11service_radius_km\x18\b \x01(\x01R\x0fserviceRadiusKm\x12\x16\n" +
	"\x06rating\x18\t \x01(\x01R\x06rating\x12!\n" +
	"\freview_count\x18\n" +
	" \x01(\x05R\vreviewCount\x12\x1f\n" +
	"\vis_verified\x18\v \x01(\bR\n" +
	"isVerified\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\"\xd6\x02\n" +
	"\bMaterial\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vsupplier_id\x18\x02 \x01(\tR\n" +
	"supplierId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x05R\x05stock\x12!\n" +
	"\fis_available\x18\a \x01(\bR\visAvailable\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\t \x01(\tR\bimageUrl\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\n" +
	" \x01(\bR\tisDeleted\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"\x88\x04\n" +
	"\tQuotation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmaterial_id\x18\x02 \x01(\tR\n" +
	"materialId\x12#\n" +
	"\rmaterial_name\x18\x03 \x01(\tR\fmaterialName\x12\x15\n" +
	"\x06job_id\x18\x04 \x01(\tR\x05jobId\x12!\n" +
	"\frequester_id\x18\x05 \x01(\tR\vrequesterId\x12\x1f\n" +
	"\vsupplier_id\x18\x06 \x01(\tR\n" +
	"supplierId\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12#\n" +
	"\rrequested_qty\x18\b \x01(\x05R\frequestedQty\x12\x14\n" +
	"\x05notes\x18\t \x01(\tR\x05notes\x12#\n" +
	"\roffered_price\x18\n" +
	" \x01(\x01R\fofferedPrice\x12#\n" +
	"\rcounter_price\x18\v \x01(\x01R\fcounterPrice\x12#\n" +
	"\ravailable_qty\x18\f \x01(\x05R\favailableQty\x12#\n" +
	"\rdelivery_date\x18\r \x01(\tR\fdeliveryDate\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x0e \x01(\tR\texpiresAt\x12!\n" +
	"\frequested_at\x18\x0f \x01(\tR\vrequestedAt\x12!\n" +
	"\fresponded_at\x18\x10 \x01(\tR\vrespondedAt\"\xd8\x01\n" +
	"\x17RegisterSupplierRequest\x12#\n" +
	"\rbusiness_name\x18\x01 \x01(\tR\fbusinessName\x12#\n" +
	"\rcontact_phone\x18\x02 \x01(\tR\fcontactPhone\x12#\n" +
	"\rcontact_email\x18\x03 \x01(\tR\fcontactEmail\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x05 \x01(\x01R\x03lng\x12*\n" +
	"\x11service_radius_km\x18\x06 \x01(\x01R\x0fserviceRadiusKm\"M\n" +
	"\x18RegisterSupplierResponse\x121\n" +
	"\bsupplier\x18\x01 \x01(\v2\x15.supplier.v1.SupplierR\bsupplier\"M\n" +
	"\x11GetProfileRequest\x12\x1f\n" +
	"\vsupplier_id\x18\x01 \x01(\tR\n" +
	"supplierId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"G\n" +
	"\x12GetProfileResponse\x121\n" +
	"\bsupplier\x18\x01 \x01(\v2\x15.supplier.v1.SupplierR\bsupplier\"\xd5\x01\n" +
	"\x14UpdateProfileRequest\x12#\n" +
	"\rbusiness_name\x18\x01 \x01(\tR\fbusinessName\x12#\n" +
	"\rcontact_phone\x18\x02 \x01(\tR\fcontactPhone\x12#\n" +
	"\rcontact_email\x18\x03 \x01(\tR\fcontactEmail\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x05 \x01(\x01R\x03lng\x12*\n" +
	"\x11service_radius_km\x18\x06 \x01(\x01R\x0fserviceRadiusKm\"J\n" +
	"\x15UpdateProfileResponse\x121\n" +
	"\bsupplier\x18\x01 \x01(\v2\x15.supplier.v1.SupplierR\bsupplier\"x\n" +
	"\x19GetNearbySuppliersRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x12\x1b\n" +
	"\tradius_km\x18\x03 \x01(\x01R\bradiusKm\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\"Q\n" +
	"\x1aGetNearbySuppliersResponse\x123\n" +
	"\tsuppliers\x18\x01 \x03(\v2\x15.supplier.v1.SupplierR\tsuppliers\"\xd2\x01\n" +
	"\x12AddMaterialRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\x12!\n" +
	"\fis_available\x18\a \x01(\bR\visAvailable\"H\n" +
	"\x13AddMaterialResponse\x121\n" +
	"\bmaterial\x18\x01 \x01(\v2\x15.supplier.v1.MaterialR\bmaterial\"\xf6\x01\n" +
	"\x15UpdateMaterialRequest\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\tR\n" +
	"materialId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\x12!\n" +
	"\fis_available\x18\b \x01(\bR\visAvailable\"K\n" +
	"\x16UpdateMaterialResponse\x121\n" +
	"\bmaterial\x18\x01 \x01(\v2\x15.supplier.v1.MaterialR\bmaterial\"<\n" +
	"\x19SoftDeleteMaterialRequest\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\tR\n" +
	"materialId\"6\n" +
	"\x1aSoftDeleteMaterialResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"}\n" +
	"\x14ListMaterialsRequest\x12\x1f\n" +
	"\vsupplier_id\x18\x01 \x01(\tR\n" +
	"supplierId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"m\n" +
	"\x15ListMaterialsResponse\x123\n" +
	"\tmaterials\x18\x01 \x03(\v2\x15.supplier.v1.MaterialR\tmaterials\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"K\n" +
	"\x12UpdateStockRequest\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\tR\n" +
	"materialId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x05R\x05delta\"2\n" +
	"\x13UpdateStockResponse\x12\x1b\n" +
	"\tnew_stock\x18\x01 \x01(\x05R\bnewStock\"\xaf\x01\n" +
	"\x12MaterialImportItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\"[\n" +
	"\x1aBulkImportMaterialsRequest\x12=\n" +
	"\tmaterials\x18\x01 \x03(\v2\x1f.supplier.v1.MaterialImportItemR\tmaterials\"\x7f\n" +
	"\x1bBulkImportMaterialsResponse\x12%\n" +
	"\x0eimported_count\x18\x01 \x01(\x05R\rimportedCount\x12!\n" +
	"\ffailed_count\x18\x02 \x01(\x05R\vfailedCount\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\"\x8c\x01\n" +
	"\x17RequestQuotationRequest\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\tR\n" +
	"materialId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12#\n" +
	"\rrequested_qty\x18\x03 \x01(\x05R\frequestedQty\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\"P\n" +
	"\x18RequestQuotationResponse\x124\n" +
	"\tquotation\x18\x01 \x01(\v2\x16.supplier.v1.QuotationR\tquotation\"\x8b\x01\n" +
	"\x19RespondToQuotationRequest\x12!\n" +
	"\fquotation_id\x18\x01 \x01(\tR\vquotationId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x10\n" +
	"\x03qty\x18\x03 \x01(\x05R\x03qty\x12#\n" +
	"\rdelivery_date\x18\x04 \x01(\tR\fdeliveryDate\"R\n" +
	"\x1aRespondToQuotationResponse\x124\n" +
	"\tquotation\x18\x01 \x01(\v2\x16.supplier.v1.QuotationR\tquotation\"]\n" +
	"\x13CounterOfferRequest\x12!\n" +
	"\fquotation_id\x18\x01 \x01(\tR\vquotationId\x12#\n" +
	"\rcounter_price\x18\x02 \x01(\x01R\fcounterPrice\"L\n" +
	"\x14CounterOfferResponse\x124\n" +
	"\tquotation\x18\x01 \x01(\v2\x16.supplier.v1.QuotationR\tquotation\";\n" +
	"\x16AcceptQuotationRequest\x12!\n" +
	"\fquotation_id\x18\x01 \x01(\tR\vquotationId\"O\n" +
	"\x17AcceptQuotationResponse\x124\n" +
	"\tquotation\x18\x01 \x01(\v2\x16.supplier.v1.QuotationR\tquotation\";\n" +
	"\x16RejectQuotationRequest\x12!\n" +
	"\fquotation_id\x18\x01 \x01(\tR\vquotationId\"3\n" +
	"\x17RejectQuotationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa1\x01\n" +
	"\x15ListQuotationsRequest\x12\x1f\n" +
	"\vsupplier_id\x18\x01 \x01(\tR\n" +
	"supplierId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\tR\vrequesterId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"q\n" +
	"\x16ListQuotationsResponse\x126\n" +
	"\n" +
	"quotations\x18\x01 \x03(\v2\x16.supplier.v1.QuotationR\n" +
	"quotations\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount2\xdc\v\n" +
	"\x0fSupplierService\x12_\n" +
	"\x10RegisterSupplier\x12$.supplier.v1.RegisterSupplierRequest\x1a%.supplier.v1.RegisterSupplierResponse\x12M\n" +
	"\n" +
	"GetProfile\x12\x1e.supplier.v1.GetProfileRequest\x1a\x1f.supplier.v1.GetProfileResponse\x12V\n" +
	"\rUpdateProfile\x12!.supplier.v1.UpdateProfileRequest\x1a\".supplier.v1.UpdateProfileResponse\x12e\n" +
	"\x12GetNearbySuppliers\x12&.supplier.v1.GetNearbySuppliersRequest\x1a'.supplier.v1.GetNearbySuppliersResponse\x12P\n" +
	"\vAddMaterial\x12\x1f.supplier.v1.AddMaterialRequest\x1a .supplier.v1.AddMaterialResponse\x12Y\n" +
	"\x0eUpdateMaterial\x12\".supplier.v1.UpdateMaterialRequest\x1a#.supplier.v1.UpdateMaterialResponse\x12e\n" +
	"\x12SoftDeleteMaterial\x12&.supplier.v1.SoftDeleteMaterialRequest\x1a'.supplier.v1.SoftDeleteMaterialResponse\x12V\n" +
	"\rListMaterials\x12!.supplier.v1.ListMaterialsRequest\x1a\".supplier.v1.ListMaterialsResponse\x12P\n" +
	"\vUpdateStock\x12\x1f.supplier.v1.UpdateStockRequest\x1a .supplier.v1.UpdateStockResponse\x12h\n" +
	"\x13BulkImportMaterials\x12'.supplier.v1.BulkImportMaterialsRequest\x1a(.supplier.v1.BulkImportMaterialsResponse\x12_\n" +
	"\x10RequestQuotation\x12$.supplier.v1.RequestQuotationRequest\x1a%.supplier.v1.RequestQuotationResponse\x12e\n" +
	"\x12RespondToQuotation\x12&.supplier.v1.RespondToQuotationRequest\x1a'.supplier.v1.RespondToQuotationResponse\x12S\n" +
	"\fCounterOffer\x12 .supplier.v1.CounterOfferRequest\x1a!.supplier.v1.CounterOfferResponse\x12\\\n" +
	"\x0fAcceptQuotation\x12#.supplier.v1.AcceptQuotationRequest\x1a$.supplier.v1.AcceptQuotationResponse\x12\\\n" +
	"\x0fRejectQuotation\x12#.supplier.v1.RejectQuotationRequest\x1a$.supplier.v1.RejectQuotationResponse\x12Y\n" +
	"\x0eListQuotations\x12\".supplier.v1.ListQuotationsRequest\x1a#.supplier.v1.ListQuotationsResponseBUZSgithub.com/yourname/fixflow-backend/internal/adapter/grpc/pb/supplier/v1;supplierv1b\x06proto3"

var (
	file_supplier_v1_supplier_proto_rawDescOnce sync.Once
	file_supplier_v1_supplier_proto_rawDescData []byte
)

func file_supplier_v1_supplier_proto_rawDescGZIP() []byte {
	file_supplier_v1_supplier_proto_rawDescOnce.Do(func() {
		file_supplier_v1_supplier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_supplier_v1_supplier_proto_rawDesc), len(file_supplier_v1_supplier_proto_rawDesc)))
	})
	return file_supplier_v1_supplier_proto_rawDescData
}

var file_supplier_v1_supplier_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_supplier_v1_supplier_proto_goTypes = []any{
	(*Supplier)(nil),                    // 0: supplier.v1.Supplier
	(*Material)(nil),                    // 1: supplier.v1.Material
	(*Quotation)(nil),                   // 2: supplier.v1.Quotation
	(*RegisterSupplierRequest)(nil),     // 3: supplier.v1.RegisterSupplierRequest
	(*RegisterSupplierResponse)(nil),    // 4: supplier.v1.RegisterSupplierResponse
	(*GetProfileRequest)(nil),           // 5: supplier.v1.GetProfileRequest
	(*GetProfileResponse)(nil),          // 6: supplier.v1.GetProfileResponse
	(*UpdateProfileRequest)(nil),        // 7: supplier.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),       // 8: supplier.v1.UpdateProfileResponse
	(*GetNearbySuppliersRequest)(nil),   // 9: supplier.v1.GetNearbySuppliersRequest
	(*GetNearbySuppliersResponse)(nil),  // 10: supplier.v1.GetNearbySuppliersResponse
	(*AddMaterialRequest)(nil),          // 11: supplier.v1.AddMaterialRequest
	(*AddMaterialResponse)(nil),         // 12: supplier.v1.AddMaterialResponse
	(*UpdateMaterialRequest)(nil),       // 13: supplier.v1.UpdateMaterialRequest
	(*UpdateMaterialResponse)(nil),      // 14: supplier.v1.UpdateMaterialResponse
	(*SoftDeleteMaterialRequest)(nil),   // 15: supplier.v1.SoftDeleteMaterialRequest
	(*SoftDeleteMaterialResponse)(nil),  // 16: supplier.v1.SoftDeleteMaterialResponse
	(*ListMaterialsRequest)(nil),        // 17: supplier.v1.ListMaterialsRequest
	(*ListMaterialsResponse)(nil),       // 18: supplier.v1.ListMaterialsResponse
	(*UpdateStockRequest)(nil),          // 19: supplier.v1.UpdateStockRequest
	(*UpdateStockResponse)(nil),         // 20: supplier.v1.UpdateStockResponse
	(*MaterialImportItem)(nil),          // 21: supplier.v1.MaterialImportItem
	(*BulkImportMaterialsRequest)(nil),  // 22: supplier.v1.BulkImportMaterialsRequest
	(*BulkImportMaterialsResponse)(nil), // 23: supplier.v1.BulkImportMaterialsResponse
	(*RequestQuotationRequest)(nil),     // 24: supplier.v1.RequestQuotationRequest
	(*RequestQuotationResponse)(nil),    // 25: supplier.v1.RequestQuotationResponse
	(*RespondToQuotationRequest)(nil),   // 26: supplier.v1.RespondToQuotationRequest
	(*RespondToQuotationResponse)(nil),  // 27: supplier.v1.RespondToQuotationResponse
	(*CounterOfferRequest)(nil),         // 28: supplier.v1.CounterOfferRequest
	(*CounterOfferResponse)(nil),        // 29: supplier.v1.CounterOfferResponse
	(*AcceptQuotationRequest)(nil),      // 30: supplier.v1.AcceptQuotationRequest
	(*AcceptQuotationResponse)(nil),     // 31: supplier.v1.AcceptQuotationResponse
	(*RejectQuotationRequest)(nil),      // 32: supplier.v1.RejectQuotationRequest
	(*RejectQuotationResponse)(nil),     // 33: supplier.v1.RejectQuotationResponse
	(*ListQuotationsRequest)(nil),       // 34: supplier.v1.ListQuotationsRequest
	(*ListQuotationsResponse)(nil),      // 35: supplier.v1.ListQuotationsResponse
}
var file_supplier_v1_supplier_proto_depIdxs = []int32{
	0,  // 0: supplier.v1.RegisterSupplierResponse.supplier:type_name -> supplier.v1.Supplier
	0,  // 1: supplier.v1.GetProfileResponse.supplier:type_name -> supplier.v1.Supplier
	0,  // 2: supplier.v1.UpdateProfileResponse.supplier:type_name -> supplier.v1.Supplier
	0,  // 3: supplier.v1.GetNearbySuppliersResponse.suppliers:type_name -> supplier.v1.Supplier
	1,  // 4: supplier.v1.AddMaterialResponse.material:type_name -> supplier.v1.Material
	1,  // 5: supplier.v1.UpdateMaterialResponse.material:type_name -> supplier.v1.Material
	1,  // 6: supplier.v1.ListMaterialsResponse.materials:type_name -> supplier.v1.Material
	21, // 7: supplier.v1.BulkImportMaterialsRequest.materials:type_name -> supplier.v1.MaterialImportItem
	2,  // 8: supplier.v1.RequestQuotationResponse.quotation:type_name -> supplier.v1.Quotation
	2,  // 9: supplier.v1.RespondToQuotationResponse.quotation:type_name -> supplier.v1.Quotation
	2,  // 10: supplier.v1.CounterOfferResponse.quotation:type_name -> supplier.v1.Quotation
	2,  // 11: supplier.v1.AcceptQuotationResponse.quotation:type_name -> supplier.v1.Quotation
	2,  // 12: supplier.v1.ListQuotationsResponse.quotations:type_name -> supplier.v1.Quotation
	3,  // 13: supplier.v1.SupplierService.RegisterSupplier:input_type -> supplier.v1.RegisterSupplierRequest
	5,  // 14: supplier.v1.SupplierService.GetProfile:input_type -> supplier.v1.GetProfileRequest
	7,  // 15: supplier.v1.SupplierService.UpdateProfile:input_type -> supplier.v1.UpdateProfileRequest
	9,  // 16: supplier.v1.SupplierService.GetNearbySuppliers:input_type -> supplier.v1.GetNearbySuppliersRequest
	11, // 17: supplier.v1.SupplierService.AddMaterial:input_type -> supplier.v1.AddMaterialRequest
	13, // 18: supplier.v1.SupplierService.UpdateMaterial:input_type -> supplier.v1.UpdateMaterialRequest
	15, // 19: supplier.v1.SupplierService.SoftDeleteMaterial:input_type -> supplier.v1.SoftDeleteMaterialRequest
	17, // 20: supplier.v1.SupplierService.ListMaterials:input_type -> supplier.v1.ListMaterialsRequest
	19, // 21: supplier.v1.SupplierService.UpdateStock:input_type -> supplier.v1.UpdateStockRequest
	22, // 22: supplier.v1.SupplierService.BulkImportMaterials:input_type -> supplier.v1.BulkImportMaterialsRequest
	24, // 23: supplier.v1.SupplierService.RequestQuotation:input_type -> supplier.v1.RequestQuotationRequest
	26, // 24: supplier.v1.SupplierService.RespondToQuotation:input_type -> supplier.v1.RespondToQuotationRequest
	28, // 25: supplier.v1.SupplierService.CounterOffer:input_type -> supplier.v1.CounterOfferRequest
	30, // 26: supplier.v1.SupplierService.AcceptQuotation:input_type -> supplier.v1.AcceptQuotationRequest
	32, // 27: supplier.v1.SupplierService.RejectQuotation:input_type -> supplier.v1.RejectQuotationRequest
	34, // 28: supplier.v1.SupplierService.ListQuotations:input_type -> supplier.v1.ListQuotationsRequest
	4,  // 29: supplier.v1.SupplierService.RegisterSupplier:output_type -> supplier.v1.RegisterSupplierResponse
	6,  // 30: supplier.v1.SupplierService.GetProfile:output_type -> supplier.v1.GetProfileResponse
	8,  // 31: supplier.v1.SupplierService.UpdateProfile:output_type -> supplier.v1.UpdateProfileResponse
	10, // 32: supplier.v1.SupplierService.GetNearbySuppliers:output_type -> supplier.v1.GetNearbySuppliersResponse
	12, // 33: supplier.v1.SupplierService.AddMaterial:output_type -> supplier.v1.AddMaterialResponse
	14, // 34: supplier.v1.SupplierService.UpdateMaterial:output_type -> supplier.v1.UpdateMaterialResponse
	16, // 35: supplier.v1.SupplierService.SoftDeleteMaterial:output_type -> supplier.v1.SoftDeleteMaterialResponse
	18, // 36: supplier.v1.SupplierService.ListMaterials:output_type -> supplier.v1.ListMaterialsResponse
	20, // 37: supplier.v1.SupplierService.UpdateStock:output_type -> supplier.v1.UpdateStockResponse
	23, // 38: supplier.v1.SupplierService.BulkImportMaterials:output_type -> supplier.v1.BulkImportMaterialsResponse
	25, // 39: supplier.v1.SupplierService.RequestQuotation:output_type -> supplier.v1.RequestQuotationResponse
	27, // 40: supplier.v1.SupplierService.RespondToQuotation:output_type -> supplier.v1.RespondToQuotationResponse
	29, // 41: supplier.v1.SupplierService.CounterOffer:output_type -> supplier.v1.CounterOfferResponse
	31, // 42: supplier.v1.SupplierService.AcceptQuotation:output_type -> supplier.v1.AcceptQuotationResponse
	33, // 43: supplier.v1.SupplierService.RejectQuotation:output_type -> supplier.v1.RejectQuotationResponse
	35, // 44: supplier.v1.SupplierService.ListQuotations:output_type -> supplier.v1.ListQuotationsResponse
	29, // [29:45] is the sub-list for method output_type
	13, // [13:29] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_supplier_v1_supplier_proto_init() }
func file_supplier_v1_supplier_proto_init() {
	if File_supplier_v1_supplier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_supplier_v1_supplier_proto_rawDesc), len(file_supplier_v1_supplier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_supplier_v1_supplier_proto_goTypes,
		DependencyIndexes: file_supplier_v1_supplier_proto_depIdxs,
		MessageInfos:      file_supplier_v1_supplier_proto_msgTypes,
	}.Build()
	File_supplier_v1_supplier_proto = out.File
	file_supplier_v1_supplier_proto_goTypes = nil
	file_supplier_v1_supplier_proto_depIdxs = nil
}
